In [1]:
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()
engine = create_engine(os.getenv("NEON_URL"))

In [2]:
eia = pd.read_sql(
    'SELECT * FROM public."Team2_EIA_Raw_Data";',
    engine
)
print(eia.shape)
print(eia.columns)
eia.head(3)

(6831, 14)
Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
0,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,million metric tons of oil equivalent,7.10688109763967209533790268920011199378,MTOE
1,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,quadrillion Btu,.282023835219977057286209774346168941857,QBTU
2,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,terajoules,297550.897927175279431940636840975075981,TJ

In [3]:
eia.columns

Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

In [4]:
eia.shape

(6831, 14)

In [5]:
eia.info

<bound method DataFrame.info of      period productId     productName activityId activityName countryRegionId  \
0      2023        44  Primary energy          1   Production             AUT
1      2023        44  Primary energy          1   Production             AUT
2      2023        44  Primary energy          1   Production             AUT
3      2023        44  Primary energy          1   Production             BEL
4      2023        44  Primary energy          1   Production             BEL
...     ...       ...             ...        ...          ...             ...
6826   2001        29      Renewables         12   Generation             SVN
6827   2001        29      Renewables         12   Generation             SWE
6828   2001        29      Renewables         12   Generation             SWE
6829   2001        29      Renewables         12   Generation             SWE
6830   2001        29      Renewables         12   Generation             SWE

     countryRegionName countryRegionTypeId countryRegionTypeName dataFlagId  \
0              Austria                   c               Country       None
1              Austria                   c               Country       None
2              Austria                   c               Country       None
3              Belgium                   c               Country       None
4              Belgium                   c               Country       None
...                ...                 ...                   ...        ...
6826          Slovenia                   c               Country       None
6827            Sweden                   c               Country       None
6828            Sweden                   c               Country       None
6829            Sweden                   c               Country       None
6830            Sweden                   c               Country       None

     dataFlagDescription                               unitName  \
0                   None  million metric tons of oil equivalent
1                   None                        quadrillion Btu
2                   None                             terajoules
3                   None  million metric tons of oil equivalent
4                   None                        quadrillion Btu
...                  ...                                    ...
6826                None                             terajoules
6827                None                  billion kilowatthours
6828                None  million metric tons of oil equivalent
6829                None                        quadrillion Btu
6830                None                             terajoules

                                         value  unit
0     7.10688109763967209533790268920011199378  MTOE
1     .282023835219977057286209774346168941857  QBTU
2     297550.897927175279431940636840975075981    TJ
3     11.7061809334744304478466416587767595932  MTOE
4      .46453880362989242695422331563651817116  QBTU
...                                        ...   ...
6826           13726.7999999999922757931452764    TJ
6827                                    82.774  BKWH
6828             7.117282885941777028552453116  MTOE
6829                     .28243661154053210556  QBTU
6830          297986.3999999998323200896425672    TJ

[6831 rows x 14 columns]>

In [6]:
eia.dtypes

period                   object
productId                object
productName              object
activityId               object
activityName             object
countryRegionId          object
countryRegionName        object
countryRegionTypeId      object
countryRegionTypeName    object
dataFlagId               object
dataFlagDescription      object
unitName                 object
value                    object
unit                     object
dtype: object

In [7]:
eia.describe

<bound method NDFrame.describe of      period productId     productName activityId activityName countryRegionId  \
0      2023        44  Primary energy          1   Production             AUT
1      2023        44  Primary energy          1   Production             AUT
2      2023        44  Primary energy          1   Production             AUT
3      2023        44  Primary energy          1   Production             BEL
4      2023        44  Primary energy          1   Production             BEL
...     ...       ...             ...        ...          ...             ...
6826   2001        29      Renewables         12   Generation             SVN
6827   2001        29      Renewables         12   Generation             SWE
6828   2001        29      Renewables         12   Generation             SWE
6829   2001        29      Renewables         12   Generation             SWE
6830   2001        29      Renewables         12   Generation             SWE

     countryRegionName countryRegionTypeId countryRegionTypeName dataFlagId  \
0              Austria                   c               Country       None
1              Austria                   c               Country       None
2              Austria                   c               Country       None
3              Belgium                   c               Country       None
4              Belgium                   c               Country       None
...                ...                 ...                   ...        ...
6826          Slovenia                   c               Country       None
6827            Sweden                   c               Country       None
6828            Sweden                   c               Country       None
6829            Sweden                   c               Country       None
6830            Sweden                   c               Country       None

     dataFlagDescription                               unitName  \
0                   None  million metric tons of oil equivalent
1                   None                        quadrillion Btu
2                   None                             terajoules
3                   None  million metric tons of oil equivalent
4                   None                        quadrillion Btu
...                  ...                                    ...
6826                None                             terajoules
6827                None                  billion kilowatthours
6828                None  million metric tons of oil equivalent
6829                None                        quadrillion Btu
6830                None                             terajoules

                                         value  unit
0     7.10688109763967209533790268920011199378  MTOE
1     .282023835219977057286209774346168941857  QBTU
2     297550.897927175279431940636840975075981    TJ
3     11.7061809334744304478466416587767595932  MTOE
4      .46453880362989242695422331563651817116  QBTU
...                                        ...   ...
6826           13726.7999999999922757931452764    TJ
6827                                    82.774  BKWH
6828             7.117282885941777028552453116  MTOE
6829                     .28243661154053210556  QBTU
6830          297986.3999999998323200896425672    TJ

[6831 rows x 14 columns]>

In [8]:
#ma uit la media de na-uri

eia.isna().mean().sort_values(ascending=False)

#totul ok(medie 0 de NA), dataflagdescription + dataflagid le voi sterge oricum

dataFlagDescription      0.966916
dataFlagId               0.966916
productName              0.000000
activityId               0.000000
period                   0.000000
productId                0.000000
countryRegionId          0.000000
activityName             0.000000
countryRegionTypeId      0.000000
countryRegionName        0.000000
countryRegionTypeName    0.000000
unitName                 0.000000
value                    0.000000
unit                     0.000000
dtype: float64

In [9]:
#verific daca exista coduri de tari care nu coincid cu codurile iso3

eu_countries_iso3 = [
    "AUT",  # Austria
    "BEL",  # Belgium
    "BGR",  # Bulgaria
    "HRV",  # Croatia
    "CYP",  # Cyprus
    "CZE",  # Czech Republic
    "DNK",  # Denmark
    "EST",  # Estonia
    "FIN",  # Finland
    "FRA",  # France
    "DEU",  # Germany
    "GRC",  # Greece
    "HUN",  # Hungary
    "IRL",  # Ireland
    "ITA",  # Italy
    "LVA",  # Latvia
    "LTU",  # Lithuania
    "LUX",  # Luxembourg
    "MLT",  # Malta
    "NLD",  # Netherlands
    "POL",  # Poland
    "PRT",  # Portugal
    "ROU",  # Romania
    "SVK",  # Slovakia
    "SVN",  # Slovenia
    "ESP",  # Spain
    "SWE"   # Sweden
]

missing_countries = [c for c in eu_countries_iso3 if c not in eia['countryRegionId'].values]

print("Tari lipsa:", missing_countries)

Tari lipsa: []

In [10]:
#valori ne parseabile ca data
pd.to_datetime(eia['period'], errors='coerce').isna().sum()

np.int64(0)

In [11]:
eia.columns

Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

In [12]:
#ma uit la coloane si decid utilitatea lor
eia["productName"].value_counts()

productName
Primary energy    3726
Renewables        3105
Name: count, dtype: int64

In [13]:
eia["countryRegionTypeName"].value_counts()
eia["countryRegionTypeName"].unique() 

#confirm faptul ca aceasta coloana nu este utila, se poate sterge

array(['Country'], dtype=object)

In [14]:
eia["countryRegionTypeId"].value_counts()
eia["countryRegionTypeId"].unique
#acelasi lucru ca mai sus

<bound method Series.unique of 0       c
1       c
2       c
3       c
4       c
       ..
6826    c
6827    c
6828    c
6829    c
6830    c
Name: countryRegionTypeId, Length: 6831, dtype: object>

In [15]:
eia["dataFlagDescription"].value_counts()

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    226
Name: count, dtype: int64

In [16]:
eia["dataFlagId"].value_counts()

dataFlagId
5    226
Name: count, dtype: int64

In [17]:
eia[["productId", "productName", "activityName", "activityId"]].drop_duplicates().sort_values("productName")

     productId     productName activityName activityId
0           44  Primary energy   Production          1
82          44  Primary energy  Consumption          2
49          29      Renewables     Capacity          7
2346        29      Renewables   Generation         12

In [18]:
eia.head(2)

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
0,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,million metric tons of oil equivalent,7.10688109763967209533790268920011199378,MTOE
1,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,quadrillion Btu,.282023835219977057286209774346168941857,QBTU

In [19]:
#copie eia + redenumesc coloane

eia_std = eia.copy()
eia_std = eia_std.rename(columns={
    "period" : "year",
    "countryRegionId" : "country_iso3",
    "countryRegionName" : "country_name",
    "unitName" : "unit_name"

})

In [20]:
# curatam textul
for col in ['productName', 'activityName', 'unit_name']:
    eia_std[col] = (
        eia_std[col]
            .astype(str)
            .str.strip()
            .str.lower()
            .str.replace(r'\s+', '_', regex=True)
    )

In [21]:
eia_std.head(2)

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit
0,2023,44,primary_energy,1,production,AUT,Austria,c,Country,None,None,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378,MTOE
1,2023,44,primary_energy,1,production,AUT,Austria,c,Country,None,None,quadrillion_btu,.282023835219977057286209774346168941857,QBTU

In [22]:
# construire indicator_name 
eia_std['indicator_name'] = (
    eia_std['productName'] + '_' + eia_std['activityName']
)
eia_std.indicator_name.unique()

array(['primary_energy_production', 'renewables_capacity',
       'primary_energy_consumption', 'renewables_generation'],
      dtype=object)

In [23]:
# unele sunt dubluri - population_population
# Folosim .loc
eia_std.loc[
    eia_std['productName'] == eia_std['activityName'],
    'indicator_name'
] = eia_std['productName']
 
eia_std.indicator_name.unique()

array(['primary_energy_production', 'renewables_capacity',
       'primary_energy_consumption', 'renewables_generation'],
      dtype=object)

In [24]:
# construire indicator_code
eia_std['indicator_code'] = (
    eia_std['productName'].str[:4].str.upper() + "_" +
    eia_std['activityName'].str[:3].str.upper()
)
eia_std['indicator_code'].unique()

array(['PRIM_PRO', 'RENE_CAP', 'PRIM_CON', 'RENE_GEN'], dtype=object)

In [25]:
eia_std['indicator_label'] = (
    eia_std['productName'].str.replace('_', ' ').str.title()
    + " - " +
    eia_std['activityName'].str.replace('_', ' ').str.title()
)
eia_std.indicator_label.unique()

array(['Primary Energy - Production', 'Renewables - Capacity',
       'Primary Energy - Consumption', 'Renewables - Generation'],
      dtype=object)

In [26]:
# underscore
eia_std['countryRegionTypeName'] = eia_std['countryRegionTypeName'].str.lower()

In [27]:
eia_std.head()

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,44,primary_energy,1,production,AUT,Austria,c,country,None,None,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,44,primary_energy,1,production,AUT,Austria,c,country,None,None,quadrillion_btu,.282023835219977057286209774346168941857,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production
2,2023,44,primary_energy,1,production,AUT,Austria,c,country,None,None,terajoules,297550.897927175279431940636840975075981,TJ,primary_energy_production,PRIM_PRO,Primary Energy - Production
3,2023,44,primary_energy,1,production,BEL,Belgium,c,country,None,None,million_metric_tons_of_oil_equivalent,11.7061809334744304478466416587767595932,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
4,2023,44,primary_energy,1,production,BEL,Belgium,c,country,None,None,quadrillion_btu,.46453880362989242695422331563651817116,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [28]:
eia_std.dataFlagDescription.value_counts()

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    226
Name: count, dtype: int64

In [29]:
#verificam lipsuri dataflagdescription, valori inutile,  = 0
missing_pct = (
    eia_std.groupby('dataFlagDescription')['value']
           .apply(lambda x: x.isna().mean())
           .sort_values(ascending=False)
)
 
print((missing_pct * 100).round(2))

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    0.0
Name: value, dtype: float64

In [30]:
#lipsuri pe ani - 0
missing_by_year = (
    eia_std.groupby('year')['value']
           .apply(lambda x: x.isna().mean())
)
print("\nLipsuri pe an (%):")
print((missing_by_year * 100).round(2).head(20))

Lipsuri pe an (%):
year
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
Name: value, dtype: float64

In [31]:
eia_std.head(2)

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,44,primary_energy,1,production,AUT,Austria,c,country,None,None,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,44,primary_energy,1,production,AUT,Austria,c,country,None,None,quadrillion_btu,.282023835219977057286209774346168941857,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [32]:
eia_std["countryRegionTypeId"].value_counts() #stergem coloana

countryRegionTypeId
c    6831
Name: count, dtype: int64

In [33]:
eia_std["countryRegionTypeName"].value_counts() #stergem coloana

countryRegionTypeName
country    6831
Name: count, dtype: int64

In [34]:
cols_to_drop = [
    "productId", #inutil
    "productName", #redundant
    "activityId", #inutil
    "activityName", #redundant
    "countryRegionTypeId", #inutil
    "countryRegionTypeName", #inutil
    "dataFlagId", #inutil
    "dataFlagDescription" #inutil

]

eia_clean = eia_std.drop(columns = cols_to_drop)

In [35]:
eia_clean.head(2)

,year,country_iso3,country_name,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,AUT,Austria,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,AUT,Austria,quadrillion_btu,.282023835219977057286209774346168941857,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [36]:
# randuri goale + duplicate
eia_clean = eia_clean.dropna(how='all')
eia_clean = eia_clean.drop_duplicates(keep='first')

In [37]:
# aranjam coloanele similar wdi
 
eia_clean= eia_clean[[
    'country_iso3',
    'country_name',
    'year',
    'indicator_code',
    'indicator_name',
    'indicator_label',
    'unit',
    'unit_name',
    'value'
]].copy()

In [38]:
eia_clean.to_csv("eia_eu_clean.csv", index=False)

In [39]:
wdi = pd.read_csv(r"C:\Users\crist\Desktop\ADC 2024\An 2\Sem I\Fluxuri de date\Virtual-ENV\wdi_EU.csv")

In [40]:
wdi.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'country_code', 'country', 'year',
       'gdp_per_capita', 'population', 'urbanization_rate',
       'energy_use_per_capita', 'renewable_final_share', 'electricity_access',
       'investment_energy', 'gov_effectiveness', 'regulatory_quality',
       'rule_of_law', 'control_corruption', 'CO2_emissions_proc',
       'CO2_emissions_mt', 'N2O_emissions_proc', 'N2O_emissions_mt',
       'CH4_emissions_proc', 'CH4_emissions_mt'],
      dtype='object')

In [41]:
wdi.head(3)

,Unnamed: 0.1,Unnamed: 0,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,...,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,950,950,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,...,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,951,951,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,...,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199
2,952,952,AUT,Austria,2002,26334.862215,8081957.0,59.655,3771.719492,24.7,...,1.880228,1.538056,1.857913,1.915159,18.935725,73.2160,-6.115108,4.0194,-20.234970,11.3043

In [42]:
wdi["Unnamed: 0"].value_counts

<bound method IndexOpsMixin.value_counts of 0        950
1        951
2        952
3        953
4        954
       ...
643    12279
644    12280
645    12281
646    12282
647    12283
Name: Unnamed: 0, Length: 648, dtype: int64>

In [43]:
cols_to_drop = [
    "Unnamed: 0.1",
    "Unnamed: 0"
]

wdi_clean = wdi.drop(columns = cols_to_drop)

In [44]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [45]:
#media na-uri
wdi_clean.isna().mean().sort_values(ascending=False)

investment_energy        0.962963
renewable_final_share    0.083333
regulatory_quality       0.041667
gov_effectiveness        0.041667
control_corruption       0.041667
rule_of_law              0.041667
country                  0.000000
country_code             0.000000
gdp_per_capita           0.000000
year                     0.000000
energy_use_per_capita    0.000000
urbanization_rate        0.000000
electricity_access       0.000000
population               0.000000
CO2_emissions_proc       0.000000
CO2_emissions_mt         0.000000
N2O_emissions_proc       0.000000
N2O_emissions_mt         0.000000
CH4_emissions_proc       0.000000
CH4_emissions_mt         0.000000
dtype: float64

In [46]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,MTOE,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,QBTU,quadrillion_btu,.282023835219977057286209774346168941857

In [47]:
cols_to_drop = [
    "unit"    
]

eia_clean = eia_clean.drop(columns = cols_to_drop)

In [48]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,quadrillion_btu,.282023835219977057286209774346168941857

In [49]:
eia_clean["unit_name"].value_counts

<bound method IndexOpsMixin.value_counts of 0       million_metric_tons_of_oil_equivalent
1                             quadrillion_btu
2                                  terajoules
3       million_metric_tons_of_oil_equivalent
4                             quadrillion_btu
                        ...
6826                               terajoules
6827                    billion_kilowatthours
6828    million_metric_tons_of_oil_equivalent
6829                          quadrillion_btu
6830                               terajoules
Name: unit_name, Length: 6831, dtype: object>

In [50]:
pd.set_option('display.max_rows', None)
 
all_indicators = eia_clean[["indicator_name", "unit_name"]].drop_duplicates()
# all_indicators are coloane: indicator_name, unit_name
# Vrem pentru fiecare indicator lista de unități distincte
 
units_per_indicator = (
    all_indicators
    .groupby("indicator_name")["unit_name"]
    .unique()
)
units_per_indicator

indicator_name
primary_energy_consumption    [million_metric_tons_of_oil_equivalent, quadri...
primary_energy_production     [million_metric_tons_of_oil_equivalent, quadri...
renewables_capacity                                         [million_kilowatts]
renewables_generation         [billion_kilowatthours, million_metric_tons_of...
Name: unit_name, dtype: object

In [51]:
# Selectăm doar indicatorii care au mai multe unități
multi_unit_indicators = units_per_indicator[units_per_indicator.apply(len) > 1]
 
# Print frumos
for ind, units in multi_unit_indicators.items():
    print(f"$ {ind}:")
    for u in units:
        print(f"   • {u}")

$ primary_energy_consumption:
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules
$ primary_energy_production:
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules
$ renewables_generation:
   • billion_kilowatthours
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules

In [52]:
# 1. unitățile standard
preferred_units = {
    "renewables_generation": "billion_kilowatthours",
    "primary_energy_consumption": "million_metric_tons_of_oil_equivalent",
    "primary_energy_production": "million_metric_tons_of_oil_equivalent",
}
 
# 2. tabel unic de conversie
CONVERSION = {
    # ---- electricitate ----
    ("billion_kilowatthours", "billion_kilowatthours"): 1,
    ("billion_kilowatthours", "million_metric_tons_of_oil_equivalent"): 11.63,
    ("billion_kilowatthours", "quadrillion_btu"): 293.071,
    ("billion_kilowatthours", "terajoules"): 277.778,

    # ---- energie primară ----
    ("million_metric_tons_of_oil_equivalent", "million_metric_tons_of_oil_equivalent"): 1,
    ("million_metric_tons_of_oil_equivalent", "quadrillion_btu"): 25.2,
    ("million_metric_tons_of_oil_equivalent", "terajoules"): 41_868,
}

In [53]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,million_metric_tons_of_oil_equivalent,7.10688109763967209533790268920011199378
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,quadrillion_btu,.282023835219977057286209774346168941857

In [54]:
# -------------------------------------------------------------
eia_f = eia_clean.copy()
 
for ind, unit in preferred_units.items():
    # pentru indicatorul ind, păstrăm doar rândurile cu unit=preferată
    eia_f = eia_f[
        ~(
            (eia_f["indicator_name"] == ind) &
            (eia_f["unit_name"] != unit)
        )
    ]
 
# -------------------------------------------------------------
# 3. Pentru ceilalți indicatori → păstrăm doar o unitate (prima)
# -------------------------------------------------------------
other_inds = set(eia_f["indicator_name"]) - set(preferred_units.keys())
 
rows = []
for ind in other_inds:
    sub = eia_f[eia_f["indicator_name"] == ind]
    first_unit = sub["unit_name"].iloc[0]
    rows.append(sub[sub["unit_name"] == first_unit])
 
eia_f2 = pd.concat(rows, ignore_index=True)
 
# Adăugăm și indicatorii standardizați deja
eia_clean = pd.concat([
    eia_f2,
    eia_f[eia_f["indicator_name"].isin(preferred_units.keys())]
], ignore_index=True)
 
# -------------------------------------------------------------
# 4. Test: verificăm dacă fiecare indicator are o singură unitate
# -------------------------------------------------------------
print(
    eia_clean.groupby("indicator_name")["unit_name"].nunique().sort_values(ascending=False)
)

indicator_name
primary_energy_consumption    1
primary_energy_production     1
renewables_capacity           1
renewables_generation         1
Name: unit_name, dtype: int64

In [55]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,FIN,Finland,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,9.564
1,FRA,France,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,54.430487

In [56]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [57]:
eia_clean = eia_clean.rename(columns={"country_iso3": "country_code"})

In [58]:
cols_to_drop = [
    "investment_energy"    
]

wdi_clean = wdi_clean.drop(columns = cols_to_drop)

In [59]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [60]:
eia_clean.head(2)

,country_code,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,FIN,Finland,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,9.564
1,FRA,France,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,54.430487

In [61]:
wdi_clean_1 = wdi_clean.melt(
    id_vars=['country_code', 'country', 'year'],
    var_name='indicator_name',
    value_name='value'
)

In [62]:
wdi_clean_1.head(2)

  country_code  country  year  indicator_name         value
0          AUT  Austria  2000  gdp_per_capita  24487.297469
1          AUT  Austria  2001  gdp_per_capita  24430.495983

In [63]:
indicator_units = {

    "gdp_per_capita": "current US$ per capita",

    "population": "persons",

    "urbanization_rate": "percent of total population",

    "energy_use_per_capita": "kg of oil equivalent per capita",

    "renewable_final_share": "percent of final energy consumption",

    "electricity_access": "percent of population",

    "gov_effectiveness": "index",

    "regulatory_quality": "index",

    "rule_of_law": "index",

    "control_corruption": "index",

    "CO2_emissions_proc": "percent of total GHG emissions",

    "CO2_emissions_mt": "million tonnes",

    "N2O_emissions_proc": "percent of total GHG emissions",

    "N2O_emissions_mt": "million tonnes",

    "CH4_emissions_proc": "percent of total GHG emissions",

    "CH4_emissions_mt": "million tonnes"

}

 
# creem coloana unit name pe baza dictionarului
wdi_clean_1["unit_name"] = wdi_clean_1["indicator_name"].map(indicator_units)
wdi_clean_1["unit_name"].isna().sum()

np.int64(0)

In [64]:
wdi_clean_1.head(2)

,country_code,country,year,indicator_name,value,unit_name
0,AUT,Austria,2000,gdp_per_capita,24487.297469,current US$ per capita
1,AUT,Austria,2001,gdp_per_capita,24430.495983,current US$ per capita

In [65]:
eia_clean.head(2)

,country_code,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,FIN,Finland,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,9.564
1,FRA,France,2021,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,54.430487

In [66]:
wdi_clean_1 = wdi_clean_1.rename(columns={"country": "country_name"})

In [67]:
wdi_clean_1.head(2)

,country_code,country_name,year,indicator_name,value,unit_name
0,AUT,Austria,2000,gdp_per_capita,24487.297469,current US$ per capita
1,AUT,Austria,2001,gdp_per_capita,24430.495983,current US$ per capita

In [68]:
# creem wdi final
wdi_final = wdi_clean_1[[
    "country_code",
    "country_name",
    "year",
    "indicator_name",
    "unit_name",
    "value"
]].copy()
 
# creem eia final
eia_final = eia_clean[[
    "country_code",
    "country_name",
    "year",
    "indicator_name",
    "unit_name",
    "value"
]].copy()
 
eia_final["value"] = pd.to_numeric(eia_final["value"], errors="coerce")

In [69]:
all_data_long = pd.concat([wdi_final, eia_final], ignore_index=True)

In [70]:
all_data_long.head(2)

,country_code,country_name,year,indicator_name,unit_name,value
0,AUT,Austria,2000,gdp_per_capita,current US$ per capita,24487.297469
1,AUT,Austria,2001,gdp_per_capita,current US$ per capita,24430.495983

In [71]:
all_data_long["indicator_name"].unique()

array(['gdp_per_capita', 'population', 'urbanization_rate',
       'energy_use_per_capita', 'renewable_final_share',
       'electricity_access', 'gov_effectiveness', 'regulatory_quality',
       'rule_of_law', 'control_corruption', 'CO2_emissions_proc',
       'CO2_emissions_mt', 'N2O_emissions_proc', 'N2O_emissions_mt',
       'CH4_emissions_proc', 'CH4_emissions_mt', 'renewables_capacity',
       'primary_energy_production', 'primary_energy_consumption',
       'renewables_generation'], dtype=object)

In [72]:
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()
engine = create_engine(os.getenv("NEON_URL"))
print(engine)

Engine(postgresql://dsw_writer:***@ep-royal-scene-agnlimgp-pooler.c-2.eu-central-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require)

In [73]:
all_data_long.to_sql(
    "Team2_Aggragated_Data",
    engine,
    if_exists="replace",
    index= False
)

852