In [1]:
import pandas as pd
import numpy as np

import pandas as pd
import numpy as np
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()
engine = create_engine(os.getenv("NEON_URL"))

wdi = pd.read_sql(
    'SELECT * FROM public."Team2_WDI_Raw_Data";',
    engine
)

print(wdi.shape)
print(wdi.columns)
wdi.head(3)

(17290, 20)
Index(['country_code', 'country', 'year', 'gdp_per_capita', 'population',
       'urbanization_rate', 'energy_use_per_capita', 'renewable_final_share',
       'electricity_access', 'investment_energy', 'gov_effectiveness',
       'regulatory_quality', 'rule_of_law', 'control_corruption',
       'CO2_emissions_proc', 'CO2_emissions_mt', 'N2O_emissions_proc',
       'N2O_emissions_mt', 'CH4_emissions_proc', 'CH4_emissions_mt'],
      dtype='object')

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,1A,Arab World,1960,NaN,91540853.0,30.946984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1A,Arab World,1961,212.904079,93931683.0,31.698628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1A,Arab World,1962,210.819690,96428599.0,32.508828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
print(wdi.shape)

(17290, 20)

In [3]:
years_keep = list(range(2000, 2024))
wdi = wdi[wdi["year"].isin(years_keep)]
print(wdi.shape[0])

6384

In [4]:
wdi.dtypes  # tipurile detectate de pandas

country_code              object
country                   object
year                       int64
gdp_per_capita           float64
population               float64
urbanization_rate        float64
energy_use_per_capita    float64
renewable_final_share    float64
electricity_access       float64
investment_energy        float64
gov_effectiveness        float64
regulatory_quality       float64
rule_of_law              float64
control_corruption       float64
CO2_emissions_proc       float64
CO2_emissions_mt         float64
N2O_emissions_proc       float64
N2O_emissions_mt         float64
CH4_emissions_proc       float64
CH4_emissions_mt         float64
dtype: object

In [5]:
country_counts = wdi.groupby(['country_code', 'country']).size().reset_index(name='count')
print(country_counts)

    country_code                                            country  count
0             1A                                         Arab World     24
1             1W                                              World     24
2             4E        East Asia & Pacific (excluding high income)     24
3             7E      Europe & Central Asia (excluding high income)     24
4             8S                                         South Asia     24
..           ...                                                ...    ...
261           ZJ                          Latin America & Caribbean     24
262           ZM                                             Zambia     24
263           ZQ  Middle East, North Africa, Afghanistan & Pakistan     24
264           ZT                                   IDA & IBRD total     24
265           ZW                                           Zimbabwe     24

[266 rows x 3 columns]

Nu eram sigura daca codurile sunt iso2 sau iso3

In [6]:
eu_countries_iso2 = [
    "AT",  # Austria
    "BE",  # Belgium
    "BG",  # Bulgaria
    "HR",  # Croatia
    "CY",  # Cyprus
    "CZ",  # Czech Republic
    "DK",  # Denmark
    "EE",  # Estonia
    "FI",  # Finland
    "FR",  # France
    "DE",  # Germany
    "GR",  # Greece
    "HU",  # Hungary
    "IE",  # Ireland
    "IT",  # Italy
    "LV",  # Latvia
    "LT",  # Lithuania
    "LU",  # Luxembourg
    "MT",  # Malta
    "NL",  # Netherlands
    "PL",  # Poland
    "PT",  # Portugal
    "RO",  # Romania
    "SK",  # Slovakia
    "SI",  # Slovenia
    "ES",  # Spain
    "SE"   # Sweden
]

wdi_EU_countries = wdi[wdi['country_code'].isin(eu_countries_iso2)]

In [7]:
country_counts = wdi_EU_countries.groupby(['country_code', 'country']).size().reset_index(name='count')
print(country_counts)

   country_code          country  count
0            AT          Austria     24
1            BE          Belgium     24
2            BG         Bulgaria     24
3            CY           Cyprus     24
4            CZ          Czechia     24
5            DE          Germany     24
6            DK          Denmark     24
7            EE          Estonia     24
8            ES            Spain     24
9            FI          Finland     24
10           FR           France     24
11           GR           Greece     24
12           HR          Croatia     24
13           HU          Hungary     24
14           IE          Ireland     24
15           IT            Italy     24
16           LT        Lithuania     24
17           LU       Luxembourg     24
18           LV           Latvia     24
19           MT            Malta     24
20           NL      Netherlands     24
21           PL           Poland     24
22           PT         Portugal     24
23           RO          Romania     24
24           SE           Sweden     24
25           SI         Slovenia     24
26           SK  Slovak Republic     24

In [8]:
wdi_EU_countries.head(10)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
954,AT,Austria,2000,24487.297469,8011566.0,66.769024,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.333766,66.6946,-5.831294,4.0792,-16.546891,11.2408
955,AT,Austria,2001,24430.495983,8042293.0,66.840816,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.931713,71.3722,-4.540838,4.1351,-16.964127,11.1846
956,AT,Austria,2002,26334.862215,8081957.0,66.888746,3771.719492,24.7,100.0,NaN,1.880228,1.538056,1.857913,1.915159,18.932168,73.2194,-6.242209,4.0614,-17.607056,11.0980
957,AT,Austria,2003,32110.115966,8121423.0,66.926357,3956.938946,22.6,100.0,NaN,1.930461,1.537136,1.847917,1.963869,26.972419,78.1693,-6.262985,4.0605,-18.938202,10.9187
958,AT,Austria,2004,36614.250653,8171966.0,66.955861,3974.506368,23.2,100.0,NaN,1.843771,1.514103,1.816664,2.026624,29.310474,79.6087,-18.172584,3.5446,-20.236681,10.7438
959,AT,Austria,2005,38157.370229,8227829.0,66.979795,4084.352619,24.4,100.0,NaN,1.679529,1.604957,1.847250,1.912423,30.618056,80.4137,-17.939425,3.5547,-22.783156,10.4008
960,AT,Austria,2006,40382.207830,8268641.0,67.000697,4105.075250,26.6,100.0,NaN,1.827385,1.644411,1.899769,1.904877,27.138750,78.2717,-18.417286,3.5340,-23.289481,10.3326
961,AT,Austria,2007,46622.962291,8295487.0,67.021104,4010.095149,29.0,100.0,NaN,1.863566,1.691164,1.941826,2.003345,22.542557,75.4421,-19.497668,3.4872,-24.162559,10.2150
962,AT,Austria,2008,51581.398236,8321496.0,67.043556,4027.905566,29.7,100.0,NaN,1.771658,1.606452,1.910699,1.828758,22.216718,75.2415,-20.404913,3.4479,-25.398676,10.0485
963,AT,Austria,2009,47857.444664,8343323.0,67.070590,3819.499869,31.3,100.0,NaN,1.662739,1.450019,1.777443,1.694034,10.551946,68.0602,-22.344060,3.3639,-26.857516,9.8520

In [9]:
wdi_EU_countries.head(3)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
954,AT,Austria,2000,24487.297469,8011566.0,66.769024,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.333766,66.6946,-5.831294,4.0792,-16.546891,11.2408
955,AT,Austria,2001,24430.495983,8042293.0,66.840816,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.931713,71.3722,-4.540838,4.1351,-16.964127,11.1846
956,AT,Austria,2002,26334.862215,8081957.0,66.888746,3771.719492,24.7,100.0,NaN,1.880228,1.538056,1.857913,1.915159,18.932168,73.2194,-6.242209,4.0614,-17.607056,11.0980

In [10]:
# ISO2
eu_countries_iso2 = [
    "AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR",
    "DE","GR","HU","IE","IT","LV","LT","LU","MT","NL",
    "PL","PT","RO","SK","SI","ES","SE"
]

# ISO3 corespunzătoare
eu_countries_iso3 = [
    "AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA",
    "DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD",
    "POL","PRT","ROU","SVK","SVN","ESP","SWE"
]

In [11]:
# Dicționar de conversie
iso2_to_iso3 = dict(zip(eu_countries_iso2, eu_countries_iso3))

# Inlocuire ISO2 cu ISO3 în DataFrame
wdi_EU_countries['country_code'] = wdi_EU_countries['country_code'].replace(iso2_to_iso3)

C:\Users\crist\AppData\Local\Temp\ipykernel_36776\3557997534.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdi_EU_countries['country_code'] = wdi_EU_countries['country_code'].replace(iso2_to_iso3)

In [12]:
wdi_EU_countries.head(3)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
954,AUT,Austria,2000,24487.297469,8011566.0,66.769024,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.333766,66.6946,-5.831294,4.0792,-16.546891,11.2408
955,AUT,Austria,2001,24430.495983,8042293.0,66.840816,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.931713,71.3722,-4.540838,4.1351,-16.964127,11.1846
956,AUT,Austria,2002,26334.862215,8081957.0,66.888746,3771.719492,24.7,100.0,NaN,1.880228,1.538056,1.857913,1.915159,18.932168,73.2194,-6.242209,4.0614,-17.607056,11.0980

In [13]:
print(wdi_EU_countries.shape[0])

648

In [14]:
wdi_EU_countries.columns

Index(['country_code', 'country', 'year', 'gdp_per_capita', 'population',
       'urbanization_rate', 'energy_use_per_capita', 'renewable_final_share',
       'electricity_access', 'investment_energy', 'gov_effectiveness',
       'regulatory_quality', 'rule_of_law', 'control_corruption',
       'CO2_emissions_proc', 'CO2_emissions_mt', 'N2O_emissions_proc',
       'N2O_emissions_mt', 'CH4_emissions_proc', 'CH4_emissions_mt'],
      dtype='object')

In [15]:
wdi_EU_countries["country"].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Cyprus', 'Czechia', 'Germany',
       'Denmark', 'Estonia', 'Spain', 'Finland', 'France', 'Greece',
       'Croatia', 'Hungary', 'Ireland', 'Italy', 'Lithuania',
       'Luxembourg', 'Latvia', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Sweden', 'Slovenia', 'Slovak Republic'],
      dtype=object)

In [16]:
print(wdi_EU_countries["CO2_emissions_proc"])

954       8.333766
955      15.931713
956      18.932168
957      26.972419
958      29.310474
           ...
12309   -42.595011
12310   -46.163094
12311   -39.558966
12312   -45.264601
12313   -48.629665
Name: CO2_emissions_proc, Length: 648, dtype: float64

In [17]:
wdi_EU_countries.duplicated(subset=['country_code','year']).sum()

np.int64(0)

## Import in Neon

In [18]:
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()
engine = create_engine(os.getenv("NEON_URL"))
print(engine)

Engine(postgresql://dsw_writer:***@ep-royal-scene-agnlimgp-pooler.c-2.eu-central-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require)

In [19]:
wdi_EU_countries.to_sql(
    "Team2_WDI_Clean_Data",
    engine,
    if_exists="replace",
    index= False
)

648