In [198]:
import pandas as pd
import numpy as np

In [199]:
eia = pd.read_csv(r"C:\Users\ASUS\Desktop\ADC 2\FLUXURI DE LUCRU PENTRU STIINTA DATELOR\dateEIA.csv")
print(eia.shape)
print(eia.columns)
eia.head(3)

(6831, 14)
Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
0,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,NaN,NaN,million metric tons of oil equivalent,7.106881,MTOE
1,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,NaN,NaN,quadrillion Btu,0.282024,QBTU
2,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,NaN,NaN,terajoules,297550.897927,TJ

In [200]:
eia.columns

Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

In [201]:
eia.shape

(6831, 14)

In [202]:
eia.info

<bound method DataFrame.info of       period  productId     productName  activityId activityName  \
0       2023         44  Primary energy           1   Production
1       2023         44  Primary energy           1   Production
2       2023         44  Primary energy           1   Production
3       2023         44  Primary energy           1   Production
4       2023         44  Primary energy           1   Production
5       2023         44  Primary energy           1   Production
6       2023         44  Primary energy           1   Production
7       2023         44  Primary energy           1   Production
8       2023         44  Primary energy           1   Production
9       2023         44  Primary energy           1   Production
10      2023         44  Primary energy           1   Production
11      2023         44  Primary energy           1   Production
12      2023         44  Primary energy           1   Production
13      2023         44  Primary energy           1   Production
14      2023         44  Primary energy           1   Production
15      2023         44  Primary energy           1   Production
16      2023         44  Primary energy           1   Production
17      2023         44  Primary energy           1   Production
18      2023         44  Primary energy           1   Production
19      2023         44  Primary energy           1   Production
20      2023         44  Primary energy           1   Production
21      2023         44  Primary energy           1   Production
22      2023         44  Primary energy           1   Production
23      2023         44  Primary energy           1   Production
24      2023         44  Primary energy           1   Production
25      2023         44  Primary energy           1   Production
26      2023         44  Primary energy           1   Production
27      2023         44  Primary energy           1   Production
28      2023         44  Primary energy           1   Production
29      2023         44  Primary energy           1   Production
30      2023         44  Primary energy           1   Production
31      2023         44  Primary energy           1   Production
32      2023         44  Primary energy           1   Production
33      2023         44  Primary energy           1   Production
34      2023         44  Primary energy           1   Production
35      2023         44  Primary energy           1   Production
36      2023         44  Primary energy           1   Production
37      2023         44  Primary energy           1   Production
38      2023         44  Primary energy           1   Production
39      2023         44  Primary energy           1   Production
40      2023         44  Primary energy           1   Production
41      2023         44  Primary energy           1   Production
42      2023         44  Primary energy           1   Production
43      2023         44  Primary energy           1   Production
44      2023         44  Primary energy           1   Production
45      2023         44  Primary energy           1   Production
46      2023         44  Primary energy           1   Production
47      2023         44  Primary energy           1   Production
48      2023         44  Primary energy           1   Production
49      2023         44  Primary energy           1   Production
50      2023         44  Primary energy           1   Production
51      2023         44  Primary energy           1   Production
52      2023         44  Primary energy           1   Production
53      2023         44  Primary energy           1   Production
54      2023         44  Primary energy           1   Production
55      2023         44  Primary energy           1   Production
56      2023         44  Primary energy           1   Production
57      2023         44  Primary energy           1   Production
58      2023         44  Primary energy           1   Production
59      2023         44  Primary energy           1   Production
60      2023         44  Primary energy           1   Production
61      2023         44  Primary energy           1   Production
62      2023         44  Primary energy           1   Production
63      2023         44  Primary energy           1   Production
64      2023         44  Primary energy           1   Production
65      2023         44  Primary energy           1   Production
66      2023         44  Primary energy           1   Production
67      2023         44  Primary energy           1   Production
68      2023         44  Primary energy           1   Production
69      2023         44  Primary energy           1   Production
70      2023         44  Primary energy           1   Production
71      2023         44  Primary energy           1   Production
72      2023         44  Primary energy           1   Production
73      2023         44  Primary energy           1   Production
74      2023         44  Primary energy           1   Production
75      2023         44  Primary energy           1   Production
76      2023         44  Primary energy           1   Production
77      2023         44  Primary energy           1   Production
78      2023         44  Primary energy           1   Production
79      2023         44  Primary energy           1   Production
80      2023         44  Primary energy           1   Production
81      2023         44  Primary energy           2  Consumption
82      2023         44  Primary energy           2  Consumption
83      2023         44  Primary energy           2  Consumption
84      2023         44  Primary energy           2  Consumption
85      2023         44  Primary energy           2  Consumption
86      2023         44  Primary energy           2  Consumption
87      2023         44  Primary energy           2  Consumption
88      2023         44  Primary energy           2  Consumption
89      2023         44  Primary energy           2  Consumption
90      2023         44  Primary energy           2  Consumption
91      2023         44  Primary energy           2  Consumption
92      2023         44  Primary energy           2  Consumption
93      2023         44  Primary energy           2  Consumption
94      2023         44  Primary energy           2  Consumption
95      2023         44  Primary energy           2  Consumption
96      2023         44  Primary energy           2  Consumption
97      2023         44  Primary energy           2  Consumption
98      2023         44  Primary energy           2  Consumption
99      2023         44  Primary energy           2  Consumption
100     2023         44  Primary energy           2  Consumption
101     2023         44  Primary energy           2  Consumption
102     2023         44  Primary energy           2  Consumption
103     2023         44  Primary energy           2  Consumption
104     2023         44  Primary energy           2  Consumption
105     2023         44  Primary energy           2  Consumption
106     2023         44  Primary energy           2  Consumption
107     2023         44  Primary energy           2  Consumption
108     2023         44  Primary energy           2  Consumption
109     2023         44  Primary energy           2  Consumption
110     2023         44  Primary energy           2  Consumption
111     2023         44  Primary energy           2  Consumption
112     2023         44  Primary energy           2  Consumption
113     2023         44  Primary energy           2  Consumption
114     2023         44  Primary energy           2  Consumption
115     2023         44  Primary energy           2  Consumption
116     2023         44  Primary energy           2  Consumption
117     2023         44  Primary energy           2  Consumption
118     2023         44  Primary energy           2  Consumption
119     2023         44  Primary energy           2  Consumption
120     2023         44  Primary energy           2  Consumption
121     2023         44  Primary energy           2  Consumption
122     2023         44  Primary energy           2  Consumption
123     2023         44  Primary energy           2  Consumption
124     2023         44  Primary energy           2  Consumption
125     2023         44  Primary energy           2  Consumption
126     2023         44  Primary energy           2  Consumption
127     2023         44  Primary energy           2  Consumption
128     2023         44  Primary energy           2  Consumption
129     2023         44  Primary energy           2  Consumption
130     2023         44  Primary energy           2  Consumption
131     2023         44  Primary energy           2  Consumption
132     2023         44  Primary energy           2  Consumption
133     2023         44  Primary energy           2  Consumption
134     2023         44  Primary energy           2  Consumption
135     2023         44  Primary energy           2  Consumption
136     2023         44  Primary energy           2  Consumption
137     2023         44  Primary energy           2  Consumption
138     2023         44  Primary energy           2  Consumption
139     2023         44  Primary energy           2  Consumption
140     2023         44  Primary energy           2  Consumption
141     2023         44  Primary energy           2  Consumption
142     2023         44  Primary energy           2  Consumption
143     2023         44  Primary energy           2  Consumption
144     2023         44  Primary energy           2  Consumption
145     2023         44  Primary energy           2  Consumption
146     2023         44  Primary energy           2  Consumption
147     2023         44  Primary energy           2  Consumption
148     2023         44  Primary energy           2  Consumption
149     2023         44  Primary energy           2  Consumption
150     2023         44  Primary energy           2  Consumption
151     2023         44  Primary energy           2  Consumption
152     2023         44  Primary energy           2  Consumption
153     2023         44  Primary energy           2  Consumption
154     2023         44  Primary energy           2  Consumption
155     2023         44  Primary energy           2  Consumption
156     2023         44  Primary energy           2  Consumption
157     2023         44  Primary energy           2  Consumption
158     2023         44  Primary energy           2  Consumption
159     2023         44  Primary energy           2  Consumption
160     2023         44  Primary energy           2  Consumption
161     2023         44  Primary energy           2  Consumption
162     2022         44  Primary energy           1   Production
163     2022         44  Primary energy           1   Production
164     2022         44  Primary energy           1   Production
165     2022         44  Primary energy           1   Production
166     2022         44  Primary energy           1   Production
167     2022         44  Primary energy           1   Production
168     2022         44  Primary energy           1   Production
169     2022         44  Primary energy           1   Production
170     2022         44  Primary energy           1   Production
171     2022         44  Primary energy           1   Production
172     2022         44  Primary energy           1   Production
173     2022         44  Primary energy           1   Production
174     2022         44  Primary energy           1   Production
175     2022         44  Primary energy           1   Production
176     2022         44  Primary energy           1   Production
177     2022         44  Primary energy           1   Production
178     2022         44  Primary energy           1   Production
179     2022         44  Primary energy           1   Production
180     2022         44  Primary energy           1   Production
181     2022         44  Primary energy           1   Production
182     2022         44  Primary energy           1   Production
183     2022         44  Primary energy           1   Production
184     2022         44  Primary energy           1   Production
185     2022         44  Primary energy           1   Production
186     2022         44  Primary energy           1   Production
187     2022         44  Primary energy           1   Production
188     2022         44  Primary energy           1   Production
189     2022         44  Primary energy           1   Production
190     2022         44  Primary energy           1   Production
191     2022         44  Primary energy           1   Production
192     2022         44  Primary energy           1   Production
193     2022         44  Primary energy           1   Production
194     2022         44  Primary energy           1   Production
195     2022         44  Primary energy           1   Production
196     2022         44  Primary energy           1   Production
197     2022         44  Primary energy           1   Production
198     2022         44  Primary energy           1   Production
199     2022         44  Primary energy           1   Production
200     2022         44  Primary energy           1   Production
201     2022         44  Primary energy           1   Production
202     2022         44  Primary energy           1   Production
203     2022         44  Primary energy           1   Production
204     2022         44  Primary energy           1   Production
205     2022         44  Primary energy           1   Production
206     2022         44  Primary energy           1   Production
207     2022         44  Primary energy           1   Production
208     2022         44  Primary energy           1   Production
209     2022         44  Primary energy           1   Production
210     2022         44  Primary energy           1   Production
211     2022         44  Primary energy           1   Production
212     2022         44  Primary energy           1   Production
213     2022         44  Primary energy           1   Production
214     2022         44  Primary energy           1   Production
215     2022         44  Primary energy           1   Production
216     2022         44  Primary energy           1   Production
217     2022         44  Primary energy           1   Production
218     2022         44  Primary energy           1   Production
219     2022         44  Primary energy           1   Production
220     2022         44  Primary energy           1   Production
221     2022         44  Primary energy           1   Production
222     2022         44  Primary energy           1   Production
223     2022         44  Primary energy           1   Production
224     2022         44  Primary energy           1   Production
225     2022         44  Primary energy           1   Production
226     2022         44  Primary energy           1   Production
227     2022         44  Primary energy           1   Production
228     2022         44  Primary energy           1   Production
229     2022         44  Primary energy           1   Production
230     2022         44  Primary energy           1   Production
231     2022         44  Primary energy           1   Production
232     2022         44  Primary energy           1   Production
233     2022         44  Primary energy           1   Production
234     2022         44  Primary energy           1   Production
235     2022         44  Primary energy           1   Production
236     2022         44  Primary energy           1   Production
237     2022         44  Primary energy           1   Production
238     2022         44  Primary energy           1   Production
239     2022         44  Primary energy           1   Production
240     2022         44  Primary energy           1   Production
241     2022         44  Primary energy           1   Production
242     2022         44  Primary energy           1   Production
243     2022         44  Primary energy           2  Consumption
244     2022         44  Primary energy           2  Consumption
245     2022         44  Primary energy           2  Consumption
246     2022         44  Primary energy           2  Consumption
247     2022         44  Primary energy           2  Consumption
248     2022         44  Primary energy           2  Consumption
249     2022         44  Primary energy           2  Consumption
250     2022         44  Primary energy           2  Consumption
251     2022         44  Primary energy           2  Consumption
252     2022         44  Primary energy           2  Consumption
253     2022         44  Primary energy           2  Consumption
254     2022         44  Primary energy           2  Consumption
255     2022         44  Primary energy           2  Consumption
256     2022         44  Primary energy           2  Consumption
257     2022         44  Primary energy           2  Consumption
258     2022         44  Primary energy           2  Consumption
259     2022         44  Primary energy           2  Consumption
260     2022         44  Primary energy           2  Consumption
261     2022         44  Primary energy           2  Consumption
262     2022         44  Primary energy           2  Consumption
263     2022         44  Primary energy           2  Consumption
264     2022         44  Primary energy           2  Consumption
265     2022         44  Primary energy           2  Consumption
266     2022         44  Primary energy           2  Consumption
267     2022         44  Primary energy           2  Consumption
268     2022         44  Primary energy           2  Consumption
269     2022         44  Primary energy           2  Consumption
270     2022         44  Primary energy           2  Consumption
271     2022         44  Primary energy           2  Consumption
272     2022         44  Primary energy           2  Consumption
273     2022         44  Primary energy           2  Consumption
274     2022         44  Primary energy           2  Consumption
275     2022         44  Primary energy           2  Consumption
276     2022         44  Primary energy           2  Consumption
277     2022         44  Primary energy           2  Consumption
278     2022         44  Primary energy           2  Consumption
279     2022         44  Primary energy           2  Consumption
280     2022         44  Primary energy           2  Consumption
281     2022         44  Primary energy           2  Consumption
282     2022         44  Primary energy           2  Consumption
283     2022         44  Primary energy           2  Consumption
284     2022         44  Primary energy           2  Consumption
285     2022         44  Primary energy           2  Consumption
286     2022         44  Primary energy           2  Consumption
287     2022         44  Primary energy           2  Consumption
288     2022         44  Primary energy           2  Consumption
289     2022         44  Primary energy           2  Consumption
290     2022         44  Primary energy           2  Consumption
291     2022         44  Primary energy           2  Consumption
292     2022         44  Primary energy           2  Consumption
293     2022         44  Primary energy           2  Consumption
294     2022         44  Primary energy           2  Consumption
295     2022         44  Primary energy           2  Consumption
296     2022         44  Primary energy           2  Consumption
297     2022         44  Primary energy           2  Consumption
298     2022         44  Primary energy           2  Consumption
299     2022         44  Primary energy           2  Consumption
300     2022         44  Primary energy           2  Consumption
301     2022         44  Primary energy           2  Consumption
302     2022         44  Primary energy           2  Consumption
303     2022         44  Primary energy           2  Consumption
304     2022         44  Primary energy           2  Consumption
305     2022         44  Primary energy           2  Consumption

In [203]:
eia.dtypes

period                     int64
productId                  int64
productName               object
activityId                 int64
activityName              object
countryRegionId           object
countryRegionName         object
countryRegionTypeId       object
countryRegionTypeName     object
dataFlagId               float64
dataFlagDescription       object
unitName                  object
value                    float64
unit                      object
dtype: object

In [204]:
eia.describe

<bound method NDFrame.describe of       period  productId     productName  activityId activityName  \
0       2023         44  Primary energy           1   Production
1       2023         44  Primary energy           1   Production
2       2023         44  Primary energy           1   Production
3       2023         44  Primary energy           1   Production
4       2023         44  Primary energy           1   Production
5       2023         44  Primary energy           1   Production
6       2023         44  Primary energy           1   Production
7       2023         44  Primary energy           1   Production
8       2023         44  Primary energy           1   Production
9       2023         44  Primary energy           1   Production
10      2023         44  Primary energy           1   Production
11      2023         44  Primary energy           1   Production
12      2023         44  Primary energy           1   Production
13      2023         44  Primary energy           1   Production
14      2023         44  Primary energy           1   Production
15      2023         44  Primary energy           1   Production
16      2023         44  Primary energy           1   Production
17      2023         44  Primary energy           1   Production
18      2023         44  Primary energy           1   Production
19      2023         44  Primary energy           1   Production
20      2023         44  Primary energy           1   Production
21      2023         44  Primary energy           1   Production
22      2023         44  Primary energy           1   Production
23      2023         44  Primary energy           1   Production
24      2023         44  Primary energy           1   Production
25      2023         44  Primary energy           1   Production
26      2023         44  Primary energy           1   Production
27      2023         44  Primary energy           1   Production
28      2023         44  Primary energy           1   Production
29      2023         44  Primary energy           1   Production
30      2023         44  Primary energy           1   Production
31      2023         44  Primary energy           1   Production
32      2023         44  Primary energy           1   Production
33      2023         44  Primary energy           1   Production
34      2023         44  Primary energy           1   Production
35      2023         44  Primary energy           1   Production
36      2023         44  Primary energy           1   Production
37      2023         44  Primary energy           1   Production
38      2023         44  Primary energy           1   Production
39      2023         44  Primary energy           1   Production
40      2023         44  Primary energy           1   Production
41      2023         44  Primary energy           1   Production
42      2023         44  Primary energy           1   Production
43      2023         44  Primary energy           1   Production
44      2023         44  Primary energy           1   Production
45      2023         44  Primary energy           1   Production
46      2023         44  Primary energy           1   Production
47      2023         44  Primary energy           1   Production
48      2023         44  Primary energy           1   Production
49      2023         44  Primary energy           1   Production
50      2023         44  Primary energy           1   Production
51      2023         44  Primary energy           1   Production
52      2023         44  Primary energy           1   Production
53      2023         44  Primary energy           1   Production
54      2023         44  Primary energy           1   Production
55      2023         44  Primary energy           1   Production
56      2023         44  Primary energy           1   Production
57      2023         44  Primary energy           1   Production
58      2023         44  Primary energy           1   Production
59      2023         44  Primary energy           1   Production
60      2023         44  Primary energy           1   Production
61      2023         44  Primary energy           1   Production
62      2023         44  Primary energy           1   Production
63      2023         44  Primary energy           1   Production
64      2023         44  Primary energy           1   Production
65      2023         44  Primary energy           1   Production
66      2023         44  Primary energy           1   Production
67      2023         44  Primary energy           1   Production
68      2023         44  Primary energy           1   Production
69      2023         44  Primary energy           1   Production
70      2023         44  Primary energy           1   Production
71      2023         44  Primary energy           1   Production
72      2023         44  Primary energy           1   Production
73      2023         44  Primary energy           1   Production
74      2023         44  Primary energy           1   Production
75      2023         44  Primary energy           1   Production
76      2023         44  Primary energy           1   Production
77      2023         44  Primary energy           1   Production
78      2023         44  Primary energy           1   Production
79      2023         44  Primary energy           1   Production
80      2023         44  Primary energy           1   Production
81      2023         44  Primary energy           2  Consumption
82      2023         44  Primary energy           2  Consumption
83      2023         44  Primary energy           2  Consumption
84      2023         44  Primary energy           2  Consumption
85      2023         44  Primary energy           2  Consumption
86      2023         44  Primary energy           2  Consumption
87      2023         44  Primary energy           2  Consumption
88      2023         44  Primary energy           2  Consumption
89      2023         44  Primary energy           2  Consumption
90      2023         44  Primary energy           2  Consumption
91      2023         44  Primary energy           2  Consumption
92      2023         44  Primary energy           2  Consumption
93      2023         44  Primary energy           2  Consumption
94      2023         44  Primary energy           2  Consumption
95      2023         44  Primary energy           2  Consumption
96      2023         44  Primary energy           2  Consumption
97      2023         44  Primary energy           2  Consumption
98      2023         44  Primary energy           2  Consumption
99      2023         44  Primary energy           2  Consumption
100     2023         44  Primary energy           2  Consumption
101     2023         44  Primary energy           2  Consumption
102     2023         44  Primary energy           2  Consumption
103     2023         44  Primary energy           2  Consumption
104     2023         44  Primary energy           2  Consumption
105     2023         44  Primary energy           2  Consumption
106     2023         44  Primary energy           2  Consumption
107     2023         44  Primary energy           2  Consumption
108     2023         44  Primary energy           2  Consumption
109     2023         44  Primary energy           2  Consumption
110     2023         44  Primary energy           2  Consumption
111     2023         44  Primary energy           2  Consumption
112     2023         44  Primary energy           2  Consumption
113     2023         44  Primary energy           2  Consumption
114     2023         44  Primary energy           2  Consumption
115     2023         44  Primary energy           2  Consumption
116     2023         44  Primary energy           2  Consumption
117     2023         44  Primary energy           2  Consumption
118     2023         44  Primary energy           2  Consumption
119     2023         44  Primary energy           2  Consumption
120     2023         44  Primary energy           2  Consumption
121     2023         44  Primary energy           2  Consumption
122     2023         44  Primary energy           2  Consumption
123     2023         44  Primary energy           2  Consumption
124     2023         44  Primary energy           2  Consumption
125     2023         44  Primary energy           2  Consumption
126     2023         44  Primary energy           2  Consumption
127     2023         44  Primary energy           2  Consumption
128     2023         44  Primary energy           2  Consumption
129     2023         44  Primary energy           2  Consumption
130     2023         44  Primary energy           2  Consumption
131     2023         44  Primary energy           2  Consumption
132     2023         44  Primary energy           2  Consumption
133     2023         44  Primary energy           2  Consumption
134     2023         44  Primary energy           2  Consumption
135     2023         44  Primary energy           2  Consumption
136     2023         44  Primary energy           2  Consumption
137     2023         44  Primary energy           2  Consumption
138     2023         44  Primary energy           2  Consumption
139     2023         44  Primary energy           2  Consumption
140     2023         44  Primary energy           2  Consumption
141     2023         44  Primary energy           2  Consumption
142     2023         44  Primary energy           2  Consumption
143     2023         44  Primary energy           2  Consumption
144     2023         44  Primary energy           2  Consumption
145     2023         44  Primary energy           2  Consumption
146     2023         44  Primary energy           2  Consumption
147     2023         44  Primary energy           2  Consumption
148     2023         44  Primary energy           2  Consumption
149     2023         44  Primary energy           2  Consumption
150     2023         44  Primary energy           2  Consumption
151     2023         44  Primary energy           2  Consumption
152     2023         44  Primary energy           2  Consumption
153     2023         44  Primary energy           2  Consumption
154     2023         44  Primary energy           2  Consumption
155     2023         44  Primary energy           2  Consumption
156     2023         44  Primary energy           2  Consumption
157     2023         44  Primary energy           2  Consumption
158     2023         44  Primary energy           2  Consumption
159     2023         44  Primary energy           2  Consumption
160     2023         44  Primary energy           2  Consumption
161     2023         44  Primary energy           2  Consumption
162     2022         44  Primary energy           1   Production
163     2022         44  Primary energy           1   Production
164     2022         44  Primary energy           1   Production
165     2022         44  Primary energy           1   Production
166     2022         44  Primary energy           1   Production
167     2022         44  Primary energy           1   Production
168     2022         44  Primary energy           1   Production
169     2022         44  Primary energy           1   Production
170     2022         44  Primary energy           1   Production
171     2022         44  Primary energy           1   Production
172     2022         44  Primary energy           1   Production
173     2022         44  Primary energy           1   Production
174     2022         44  Primary energy           1   Production
175     2022         44  Primary energy           1   Production
176     2022         44  Primary energy           1   Production
177     2022         44  Primary energy           1   Production
178     2022         44  Primary energy           1   Production
179     2022         44  Primary energy           1   Production
180     2022         44  Primary energy           1   Production
181     2022         44  Primary energy           1   Production
182     2022         44  Primary energy           1   Production
183     2022         44  Primary energy           1   Production
184     2022         44  Primary energy           1   Production
185     2022         44  Primary energy           1   Production
186     2022         44  Primary energy           1   Production
187     2022         44  Primary energy           1   Production
188     2022         44  Primary energy           1   Production
189     2022         44  Primary energy           1   Production
190     2022         44  Primary energy           1   Production
191     2022         44  Primary energy           1   Production
192     2022         44  Primary energy           1   Production
193     2022         44  Primary energy           1   Production
194     2022         44  Primary energy           1   Production
195     2022         44  Primary energy           1   Production
196     2022         44  Primary energy           1   Production
197     2022         44  Primary energy           1   Production
198     2022         44  Primary energy           1   Production
199     2022         44  Primary energy           1   Production
200     2022         44  Primary energy           1   Production
201     2022         44  Primary energy           1   Production
202     2022         44  Primary energy           1   Production
203     2022         44  Primary energy           1   Production
204     2022         44  Primary energy           1   Production
205     2022         44  Primary energy           1   Production
206     2022         44  Primary energy           1   Production
207     2022         44  Primary energy           1   Production
208     2022         44  Primary energy           1   Production
209     2022         44  Primary energy           1   Production
210     2022         44  Primary energy           1   Production
211     2022         44  Primary energy           1   Production
212     2022         44  Primary energy           1   Production
213     2022         44  Primary energy           1   Production
214     2022         44  Primary energy           1   Production
215     2022         44  Primary energy           1   Production
216     2022         44  Primary energy           1   Production
217     2022         44  Primary energy           1   Production
218     2022         44  Primary energy           1   Production
219     2022         44  Primary energy           1   Production
220     2022         44  Primary energy           1   Production
221     2022         44  Primary energy           1   Production
222     2022         44  Primary energy           1   Production
223     2022         44  Primary energy           1   Production
224     2022         44  Primary energy           1   Production
225     2022         44  Primary energy           1   Production
226     2022         44  Primary energy           1   Production
227     2022         44  Primary energy           1   Production
228     2022         44  Primary energy           1   Production
229     2022         44  Primary energy           1   Production
230     2022         44  Primary energy           1   Production
231     2022         44  Primary energy           1   Production
232     2022         44  Primary energy           1   Production
233     2022         44  Primary energy           1   Production
234     2022         44  Primary energy           1   Production
235     2022         44  Primary energy           1   Production
236     2022         44  Primary energy           1   Production
237     2022         44  Primary energy           1   Production
238     2022         44  Primary energy           1   Production
239     2022         44  Primary energy           1   Production
240     2022         44  Primary energy           1   Production
241     2022         44  Primary energy           1   Production
242     2022         44  Primary energy           1   Production
243     2022         44  Primary energy           2  Consumption
244     2022         44  Primary energy           2  Consumption
245     2022         44  Primary energy           2  Consumption
246     2022         44  Primary energy           2  Consumption
247     2022         44  Primary energy           2  Consumption
248     2022         44  Primary energy           2  Consumption
249     2022         44  Primary energy           2  Consumption
250     2022         44  Primary energy           2  Consumption
251     2022         44  Primary energy           2  Consumption
252     2022         44  Primary energy           2  Consumption
253     2022         44  Primary energy           2  Consumption
254     2022         44  Primary energy           2  Consumption
255     2022         44  Primary energy           2  Consumption
256     2022         44  Primary energy           2  Consumption
257     2022         44  Primary energy           2  Consumption
258     2022         44  Primary energy           2  Consumption
259     2022         44  Primary energy           2  Consumption
260     2022         44  Primary energy           2  Consumption
261     2022         44  Primary energy           2  Consumption
262     2022         44  Primary energy           2  Consumption
263     2022         44  Primary energy           2  Consumption
264     2022         44  Primary energy           2  Consumption
265     2022         44  Primary energy           2  Consumption
266     2022         44  Primary energy           2  Consumption
267     2022         44  Primary energy           2  Consumption
268     2022         44  Primary energy           2  Consumption
269     2022         44  Primary energy           2  Consumption
270     2022         44  Primary energy           2  Consumption
271     2022         44  Primary energy           2  Consumption
272     2022         44  Primary energy           2  Consumption
273     2022         44  Primary energy           2  Consumption
274     2022         44  Primary energy           2  Consumption
275     2022         44  Primary energy           2  Consumption
276     2022         44  Primary energy           2  Consumption
277     2022         44  Primary energy           2  Consumption
278     2022         44  Primary energy           2  Consumption
279     2022         44  Primary energy           2  Consumption
280     2022         44  Primary energy           2  Consumption
281     2022         44  Primary energy           2  Consumption
282     2022         44  Primary energy           2  Consumption
283     2022         44  Primary energy           2  Consumption
284     2022         44  Primary energy           2  Consumption
285     2022         44  Primary energy           2  Consumption
286     2022         44  Primary energy           2  Consumption
287     2022         44  Primary energy           2  Consumption
288     2022         44  Primary energy           2  Consumption
289     2022         44  Primary energy           2  Consumption
290     2022         44  Primary energy           2  Consumption
291     2022         44  Primary energy           2  Consumption
292     2022         44  Primary energy           2  Consumption
293     2022         44  Primary energy           2  Consumption
294     2022         44  Primary energy           2  Consumption
295     2022         44  Primary energy           2  Consumption
296     2022         44  Primary energy           2  Consumption
297     2022         44  Primary energy           2  Consumption
298     2022         44  Primary energy           2  Consumption
299     2022         44  Primary energy           2  Consumption
300     2022         44  Primary energy           2  Consumption
301     2022         44  Primary energy           2  Consumption
302     2022         44  Primary energy           2  Consumption
303     2022         44  Primary energy           2  Consumption
304     2022         44  Primary energy           2  Consumption
305     2022         44  Primary energy           2  Consumption

In [205]:
#ma uit la media de na-uri

eia.isna().mean().sort_values(ascending=False)

#totul ok(medie 0 de NA), dataflagdescription + dataflagid le voi sterge oricum

dataFlagDescription      0.966916
dataFlagId               0.966916
productName              0.000000
activityId               0.000000
period                   0.000000
productId                0.000000
countryRegionId          0.000000
activityName             0.000000
countryRegionTypeId      0.000000
countryRegionName        0.000000
countryRegionTypeName    0.000000
unitName                 0.000000
value                    0.000000
unit                     0.000000
dtype: float64

In [206]:
#verific daca exista coduri de tari care nu coincid cu codurile iso3

eu_countries_iso3 = [
    "AUT",  # Austria
    "BEL",  # Belgium
    "BGR",  # Bulgaria
    "HRV",  # Croatia
    "CYP",  # Cyprus
    "CZE",  # Czech Republic
    "DNK",  # Denmark
    "EST",  # Estonia
    "FIN",  # Finland
    "FRA",  # France
    "DEU",  # Germany
    "GRC",  # Greece
    "HUN",  # Hungary
    "IRL",  # Ireland
    "ITA",  # Italy
    "LVA",  # Latvia
    "LTU",  # Lithuania
    "LUX",  # Luxembourg
    "MLT",  # Malta
    "NLD",  # Netherlands
    "POL",  # Poland
    "PRT",  # Portugal
    "ROU",  # Romania
    "SVK",  # Slovakia
    "SVN",  # Slovenia
    "ESP",  # Spain
    "SWE"   # Sweden
]

missing_countries = [c for c in eu_countries_iso3 if c not in eia['countryRegionId'].values]

print("Tari lipsa:", missing_countries)

Tari lipsa: []

In [207]:
#valori ne parseabile ca data
pd.to_datetime(eia['period'], errors='coerce').isna().sum()

np.int64(0)

In [208]:
eia.columns

Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

In [209]:
#ma uit la coloane si decid utilitatea lor
eia["productName"].value_counts()

productName
Primary energy    3726
Renewables        3105
Name: count, dtype: int64

In [210]:
eia["countryRegionTypeName"].value_counts()
eia["countryRegionTypeName"].unique() 

#confirm faptul ca aceasta coloana nu este utila, se poate sterge

array(['Country'], dtype=object)

In [211]:
eia["countryRegionTypeId"].value_counts()
eia["countryRegionTypeId"].unique
#acelasi lucru ca mai sus

<bound method Series.unique of 0       c
1       c
2       c
3       c
4       c
5       c
6       c
7       c
8       c
9       c
10      c
11      c
12      c
13      c
14      c
15      c
16      c
17      c
18      c
19      c
20      c
21      c
22      c
23      c
24      c
25      c
26      c
27      c
28      c
29      c
30      c
31      c
32      c
33      c
34      c
35      c
36      c
37      c
38      c
39      c
40      c
41      c
42      c
43      c
44      c
45      c
46      c
47      c
48      c
49      c
50      c
51      c
52      c
53      c
54      c
55      c
56      c
57      c
58      c
59      c
60      c
61      c
62      c
63      c
64      c
65      c
66      c
67      c
68      c
69      c
70      c
71      c
72      c
73      c
74      c
75      c
76      c
77      c
78      c
79      c
80      c
81      c
82      c
83      c
84      c
85      c
86      c
87      c
88      c
89      c
90      c
91      c
92      c
93      c
94      c
95      c
96      c
97      c
98      c
99      c
100     c
101     c
102     c
103     c
104     c
105     c
106     c
107     c
108     c
109     c
110     c
111     c
112     c
113     c
114     c
115     c
116     c
117     c
118     c
119     c
120     c
121     c
122     c
123     c
124     c
125     c
126     c
127     c
128     c
129     c
130     c
131     c
132     c
133     c
134     c
135     c
136     c
137     c
138     c
139     c
140     c
141     c
142     c
143     c
144     c
145     c
146     c
147     c
148     c
149     c
150     c
151     c
152     c
153     c
154     c
155     c
156     c
157     c
158     c
159     c
160     c
161     c
162     c
163     c
164     c
165     c
166     c
167     c
168     c
169     c
170     c
171     c
172     c
173     c
174     c
175     c
176     c
177     c
178     c
179     c
180     c
181     c
182     c
183     c
184     c
185     c
186     c
187     c
188     c
189     c
190     c
191     c
192     c
193     c
194     c
195     c
196     c
197     c
198     c
199     c
200     c
201     c
202     c
203     c
204     c
205     c
206     c
207     c
208     c
209     c
210     c
211     c
212     c
213     c
214     c
215     c
216     c
217     c
218     c
219     c
220     c
221     c
222     c
223     c
224     c
225     c
226     c
227     c
228     c
229     c
230     c
231     c
232     c
233     c
234     c
235     c
236     c
237     c
238     c
239     c
240     c
241     c
242     c
243     c
244     c
245     c
246     c
247     c
248     c
249     c
250     c
251     c
252     c
253     c
254     c
255     c
256     c
257     c
258     c
259     c
260     c
261     c
262     c
263     c
264     c
265     c
266     c
267     c
268     c
269     c
270     c
271     c
272     c
273     c
274     c
275     c
276     c
277     c
278     c
279     c
280     c
281     c
282     c
283     c
284     c
285     c
286     c
287     c
288     c
289     c
290     c
291     c
292     c
293     c
294     c
295     c
296     c
297     c
298     c
299     c
300     c
301     c
302     c
303     c
304     c
305     c
306     c
307     c
308     c
309     c
310     c
311     c
312     c
313     c
314     c
315     c
316     c
317     c
318     c
319     c
320     c
321     c
322     c
323     c
324     c
325     c
326     c
327     c
328     c
329     c
330     c
331     c
332     c
333     c
334     c
335     c
336     c
337     c
338     c
339     c
340     c
341     c
342     c
343     c
344     c
345     c
346     c
347     c
348     c
349     c
350     c
351     c
352     c
353     c
354     c
355     c
356     c
357     c
358     c
359     c
360     c
361     c
362     c
363     c
364     c
365     c
366     c
367     c
368     c
369     c
370     c
371     c
372     c
373     c
374     c
375     c
376     c
377     c
378     c
379     c
380     c
381     c
382     c
383     c
384     c
385     c
386     c
387     c
388     c
389     c
390     c
391     c
392     c
393     c
394     c
395     c
396     c
397     c
398     c
399     c
400     c
401     c
402     c
403     c
404     c
405     c
406     c
407     c
408     c
409     c
410     c
411     c
412     c
413     c
414     c
415     c
416     c
417     c
418     c
419     c
420     c
421     c
422     c
423     c
424     c
425     c
426     c
427     c
428     c
429     c
430     c
431     c
432     c
433     c
434     c
435     c
436     c
437     c
438     c
439     c
440     c
441     c
442     c
443     c
444     c
445     c
446     c
447     c
448     c
449     c
450     c
451     c
452     c
453     c
454     c
455     c
456     c
457     c
458     c
459     c
460     c
461     c
462     c
463     c
464     c
465     c
466     c
467     c
468     c
469     c
470     c
471     c
472     c
473     c
474     c
475     c
476     c
477     c
478     c
479     c
480     c
481     c
482     c
483     c
484     c
485     c
486     c
487     c
488     c
489     c
490     c
491     c
492     c
493     c
494     c
495     c
496     c
497     c
498     c
499     c
500     c
501     c
502     c
503     c
504     c
505     c
506     c
507     c
508     c
509     c
510     c
511     c
512     c
513     c
514     c
515     c
516     c
517     c
518     c
519     c
520     c
521     c
522     c
523     c
524     c
525     c
526     c
527     c
528     c
529     c
530     c
531     c
532     c
533     c
534     c
535     c
536     c
537     c
538     c
539     c
540     c
541     c
542     c
543     c
544     c
545     c
546     c
547     c
548     c
549     c
550     c
551     c
552     c
553     c
554     c
555     c
556     c
557     c
558     c
559     c
560     c
561     c
562     c
563     c
564     c
565     c
566     c
567     c
568     c
569     c
570     c
571     c
572     c
573     c
574     c
575     c
576     c
577     c
578     c
579     c
580     c
581     c
582     c
583     c
584     c
585     c
586     c
587     c
588     c
589     c
590     c
591     c
592     c
593     c
594     c
595     c
596     c
597     c
598     c
599     c
600     c
601     c
602     c
603     c
604     c
605     c
606     c
607     c
608     c
609     c
610     c
611     c
612     c
613     c
614     c
615     c
616     c
617     c
618     c
619     c
620     c
621     c
622     c
623     c
624     c
625     c
626     c
627     c
628     c
629     c
630     c
631     c
632     c
633     c
634     c
635     c
636     c
637     c
638     c
639     c
640     c
641     c
642     c
643     c
644     c
645     c
646     c
647     c
648     c
649     c
650     c
651     c
652     c
653     c
654     c
655     c
656     c
657     c
658     c
659     c
660     c
661     c
662     c
663     c
664     c
665     c
666     c
667     c
668     c
669     c
670     c
671     c
672     c
673     c
674     c
675     c
676     c
677     c
678     c
679     c
680     c
681     c
682     c
683     c
684     c
685     c
686     c
687     c
688     c
689     c
690     c
691     c
692     c
693     c
694     c
695     c
696     c
697     c
698     c
699     c
700     c
701     c
702     c
703     c
704     c
705     c
706     c
707     c
708     c
709     c
710     c
711     c
712     c
713     c
714     c
715     c
716     c
717     c
718     c
719     c
720     c
721     c
722     c
723     c
724     c
725     c
726     c
727     c
728     c
729     c
730     c
731     c
732     c
733     c
734     c
735     c
736     c
737     c
738     c
739     c
740     c
741     c
742     c
743     c
744     c
745     c
746     c
747     c
748     c
749     c
750     c
751     c
752     c
753     c
754     c
755     c
756     c
757     c
758     c
759     c
760     c
761     c
762     c
763     c
764     c
765     c
766     c
767     c
768     c
769     c
770     c
771     c
772     c
773     c
774     c
775     c
776     c
777     c
778     c
779     c
780     c
781     c
782     c
783     c
784     c
785     c
786     c
787     c
788     c
789     c
790     c
791     c
792     c
793     c
794     c
795     c
796     c
797     c
798     c
799     c
800     c
801     c
802     c
803     c
804     c
805     c
806     c
807     c
808     c
809     c
810     c
811     c
812     c
813     c
814     c
815     c
816     c
817     c
818     c
819     c
820     c
821     c
822     c
823     c
824     c
825     c
826     c
827     c
828     c
829     c
830     c
831     c
832     c
833     c
834     c
835     c
836     c
837     c
838     c
839     c
840     c
841     c
842     c
843     c
844     c
845     c
846     c
847     c
848     c
849     c
850     c
851     c
852     c
853     c
854     c
855     c
856     c
857     c
858     c
859     c
860     c
861     c
862     c
863     c
864     c
865     c
866     c
867     c
868     c
869     c
870     c
871     c
872     c
873     c
874     c
875     c
876     c
877     c
878     c
879     c
880     c
881     c
882     c
883     c
884     c
885     c
886     c
887     c
888     c
889     c
890     c
891     c
892     c
893     c
894     c
895     c
896     c
897     c
898     c
899     c
900     c
901     c
902     c
903     c
904     c
905     c
906     c
907     c
908     c
909     c
910     c
911     c
912     c
913     c
914     c
915     c
916     c
917     c
918     c
919     c
920     c
921     c
922     c
923     c
924     c
925     c
926     c
927     c
928     c
929     c
930     c
931     c
932     c
933     c
934     c
935     c
936     c
937     c
938     c
939     c
940     c
941     c
942     c
943     c
944     c
945     c
946     c
947     c
948     c
949     c
950     c
951     c
952     c
953     c
954     c
955     c
956     c
957     c
958     c
959     c
960     c
961     c
962     c
963     c
964     c
965     c
966     c
967     c
968     c
969     c
970     c
971     c
972     c
973     c
974     c
975     c
976     c
977     c
978     c
979     c
980     c
981     c
982     c
983     c
984     c
985     c
986     c
987     c
988     c
989     c
990     c
991     c
992     c
993     c
994     c
995     c
996     c
997     c
998     c
999     c
1000    c
1001    c
1002    c
1003    c
1004    c
1005    c
1006    c
1007    c
1008    c
1009    c
1010    c
1011    c
1012    c
1013    c
1014    c
1015    c
1016    c
1017    c
1018    c
1019    c
1020    c
1021    c
1022    c
1023    c
1024    c
1025    c
1026    c
1027    c
1028    c
1029    c
1030    c
1031    c
1032    c
1033    c
1034    c
1035    c
1036    c
1037    c
1038    c
1039    c
1040    c
1041    c
1042    c
1043    c
1044    c
1045    c
1046    c
1047    c
1048    c
1049    c
1050    c
1051    c
1052    c
1053    c
1054    c
1055    c
1056    c
1057    c
1058    c
1059    c
1060    c
1061    c
1062    c
1063    c
1064    c
1065    c
1066    c
1067    c
1068    c
1069    c
1070    c
1071    c
1072    c
1073    c
1074    c
1075    c
1076    c
1077    c
1078    c
1079    c
1080    c
1081    c
1082    c
1083    c
1084    c
1085    c
1086    c
1087    c
1088    c
1089    c
1090    c
1091    c
1092    c
1093    c
1094    c
1095    c
1096    c
1097    c
1098    c
1099    c
1100    c
1101    c
1102    c
1103    c
1104    c
1105    c
1106    c
1107    c
1108    c
1109    c
1110    c
1111    c
1112    c
1113    c
1114    c
1115    c
1116    c
1117    c
1118    c
1119    c
1120    c
1121    c
1122    c
1123    c
1124    c
1125    c
1126    c
1127    c
1128    c
1129    c
1130    c
1131    c
1132    c
1133    c
1134    c
1135    c
1136    c
1137    c
1138    c
1139    c
1140    c
1141    c
1142    c
1143    c
1144    c
1145    c
1146    c
1147    c
1148    c
1149    c
1150    c
1151    c
1152    c
1153    c
1154    c
1155    c
1156    c
1157    c
1158    c
1159    c
1160    c
1161    c
1162    c
1163    c
1164    c
1165    c
1166    c
1167    c
1168    c
1169    c
1170    c
1171    c
1172    c
1173    c
1174    c
1175    c
1176    c
1177    c
1178    c
1179    c
1180    c
1181    c
1182    c
1183    c
1184    c
1185    c
1186    c
1187    c
1188    c
1189    c
1190    c
1191    c
1192    c
1193    c
1194    c
1195    c
1196    c
1197    c
1198    c
1199    c
1200    c
1201    c
1202    c
1203    c
1204    c
1205    c
1206    c
1207    c
1208    c
1209    c
1210    c
1211    c
1212    c
1213    c
1214    c
1215    c
1216    c
1217    c
1218    c
1219    c
1220    c
1221    c
1222    c
1223    c
1224    c
1225    c
1226    c
1227    c
1228    c
1229    c
1230    c
1231    c
1232    c
1233    c
1234    c
1235    c
1236    c
1237    c
1238    c
1239    c
1240    c
1241    c
1242    c
1243    c
1244    c
1245    c
1246    c
1247    c
1248    c
1249    c
1250    c
1251    c
1252    c
1253    c
1254    c
1255    c
1256    c
1257    c
1258    c
1259    c
1260    c
1261    c
1262    c
1263    c
1264    c
1265    c
1266    c
1267    c
1268    c
1269    c
1270    c
1271    c
1272    c
1273    c
1274    c
1275    c
1276    c
1277    c
1278    c
1279    c
1280    c
1281    c
1282    c
1283    c
1284    c
1285    c
1286    c
1287    c
1288    c
1289    c
1290    c
1291    c
1292    c
1293    c
1294    c
1295    c
1296    c
1297    c
1298    c
1299    c
1300    c
1301    c
1302    c
1303    c
1304    c
1305    c
1306    c
1307    c
1308    c
1309    c
1310    c
1311    c
1312    c
1313    c
1314    c
1315    c
1316    c
1317    c
1318    c
1319    c
1320    c
1321    c
1322    c
1323    c
1324    c
1325    c
1326    c
1327    c
1328    c
1329    c
1330    c
1331    c
1332    c
1333    c
1334    c
1335    c
1336    c
1337    c
1338    c
1339    c
1340    c
1341    c
1342    c
1343    c
1344    c
1345    c
1346    c
1347    c
1348    c
1349    c
1350    c
1351    c
1352    c
1353    c
1354    c
1355    c
1356    c
1357    c
1358    c
1359    c
1360    c
1361    c
1362    c
1363    c
1364    c
1365    c
1366    c
1367    c
1368    c
1369    c
1370    c
1371    c
1372    c
1373    c
1374    c
1375    c
1376    c
1377    c
1378    c
1379    c
1380    c
1381    c
1382    c
1383    c
1384    c
1385    c
1386    c
1387    c
1388    c
1389    c
1390    c
1391    c
1392    c
1393    c
1394    c
1395    c
1396    c
1397    c
1398    c
1399    c
1400    c
1401    c
1402    c
1403    c
1404    c
1405    c
1406    c
1407    c
1408    c
1409    c
1410    c
1411    c
1412    c
1413    c
1414    c
1415    c
1416    c
1417    c
1418    c
1419    c
1420    c
1421    c
1422    c
1423    c
1424    c
1425    c
1426    c
1427    c
1428    c
1429    c
1430    c
1431    c
1432    c
1433    c
1434    c
1435    c
1436    c
1437    c
1438    c
1439    c
1440    c
1441    c
1442    c
1443    c
1444    c
1445    c
1446    c
1447    c
1448    c
1449    c
1450    c
1451    c
1452    c
1453    c
1454    c
1455    c
1456    c
1457    c
1458    c
1459    c
1460    c
1461    c
1462    c
1463    c
1464    c
1465    c
1466    c
1467    c
1468    c
1469    c
1470    c
1471    c
1472    c
1473    c
1474    c
1475    c
1476    c
1477    c
1478    c
1479    c
1480    c
1481    c
1482    c
1483    c
1484    c
1485    c
1486    c
1487    c
1488    c
1489    c
1490    c
1491    c
1492    c
1493    c
1494    c
1495    c
1496    c
1497    c
1498    c
1499    c
1500    c
1501    c
1502    c
1503    c
1504    c
1505    c
1506    c
1507    c
1508    c
1509    c
1510    c
1511    c
1512    c
1513    c
1514    c
1515    c
1516    c
1517    c
1518    c
1519    c
1520    c
1521    c
1522    c
1523    c
1524    c
1525    c
1526    c
1527    c
1528    c
1529    c
1530    c
1531    c
1532    c
1533    c
1534    c
1535    c
1536    c
1537    c
1538    c
1539    c
1540    c
1541    c
1542    c
1543    c
1544    c
1545    c
1546    c
1547    c
1548    c
1549    c
1550    c
1551    c
1552    c
1553    c
1554    c
1555    c
1556    c
1557    c
1558    c
1559    c
1560    c
1561    c
1562    c
1563    c
1564    c
1565    c
1566    c
1567    c
1568    c
1569    c
1570    c
1571    c
1572    c
1573    c
1574    c
1575    c
1576    c
1577    c
1578    c
1579    c
1580    c
1581    c
1582    c
1583    c
1584    c
1585    c
1586    c
1587    c
1588    c
1589    c
1590    c
1591    c
1592    c
1593    c
1594    c
1595    c
1596    c
1597    c
1598    c
1599    c
1600    c
1601    c
1602    c
1603    c
1604    c
1605    c
1606    c
1607    c
1608    c
1609    c
1610    c
1611    c
1612    c
1613    c
1614    c
1615    c
1616    c
1617    c
1618    c
1619    c
1620    c
1621    c
1622    c
1623    c
1624    c
1625    c
1626    c
1627    c
1628    c
1629    c
1630    c
1631    c
1632    c
1633    c
1634    c
1635    c
1636    c
1637    c
1638    c
1639    c
1640    c
1641    c
1642    c
1643    c
1644    c
1645    c
1646    c
1647    c
1648    c
1649    c
1650    c
1651    c
1652    c
1653    c
1654    c
1655    c
1656    c
1657    c
1658    c
1659    c
1660    c
1661    c
1662    c
1663    c
1664    c
1665    c
1666    c
1667    c
1668    c
1669    c
1670    c
1671    c
1672    c
1673    c
1674    c
1675    c
1676    c
1677    c
1678    c
1679    c
1680    c
1681    c
1682    c
1683    c
1684    c
1685    c
1686    c
1687    c
1688    c
1689    c
1690    c
1691    c
1692    c
1693    c
1694    c
1695    c
1696    c
1697    c
1698    c
1699    c
1700    c
1701    c
1702    c
1703    c
1704    c
1705    c
1706    c
1707    c
1708    c
1709    c
1710    c
1711    c
1712    c
1713    c
1714    c
1715    c
1716    c
1717    c
1718    c
1719    c
1720    c
1721    c
1722    c
1723    c
1724    c
1725    c
1726    c
1727    c
1728    c
1729    c
1730    c
1731    c
1732    c
1733    c
1734    c
1735    c
1736    c
1737    c
1738    c
1739    c
1740    c
1741    c
1742    c
1743    c
1744    c
1745    c
1746    c
1747    c
1748    c
1749    c
1750    c
1751    c
1752    c
1753    c
1754    c
1755    c
1756    c
1757    c
1758    c
1759    c
1760    c
1761    c
1762    c
1763    c
1764    c
1765    c
1766    c
1767    c
1768    c
1769    c
1770    c
1771    c
1772    c
1773    c
1774    c
1775    c
1776    c
1777    c
1778    c
1779    c
1780    c
1781    c
1782    c
1783    c
1784    c
1785    c
1786    c
1787    c
1788    c
1789    c
1790    c
1791    c
1792    c
1793    c
1794    c
1795    c
1796    c
1797    c
1798    c
1799    c
1800    c
1801    c
1802    c
1803    c
1804    c
1805    c
1806    c
1807    c
1808    c
1809    c
1810    c
1811    c
1812    c
1813    c
1814    c
1815    c
1816    c
1817    c
1818    c
1819    c
1820    c
1821    c
1822    c
1823    c
1824    c
1825    c
1826    c
1827    c
1828    c
1829    c
1830    c
1831    c
1832    c
1833    c
1834    c
1835    c
1836    c
1837    c
1838    c
1839    c
1840    c
1841    c
1842    c
1843    c
1844    c
1845    c
1846    c
1847    c
1848    c
1849    c
1850    c
1851    c
1852    c
1853    c
1854    c
1855    c
1856    c
1857    c
1858    c
1859    c
1860    c
1861    c
1862    c
1863    c
1864    c
1865    c
1866    c
1867    c
1868    c
1869    c
1870    c
1871    c
1872    c
1873    c
1874    c
1875    c
1876    c
1877    c
1878    c
1879    c
1880    c
1881    c
1882    c
1883    c
1884    c
1885    c
1886    c
1887    c
1888    c
1889    c
1890    c
1891    c
1892    c
1893    c
1894    c
1895    c
1896    c
1897    c
1898    c
1899    c
1900    c
1901    c
1902    c
1903    c
1904    c
1905    c
1906    c
1907    c
1908    c
1909    c
1910    c
1911    c
1912    c
1913    c
1914    c
1915    c
1916    c
1917    c
1918    c
1919    c
1920    c
1921    c
1922    c
1923    c
1924    c
1925    c
1926    c
1927    c
1928    c
1929    c
1930    c
1931    c
1932    c
1933    c
1934    c
1935    c
1936    c
1937    c
1938    c
1939    c
1940    c
1941    c
1942    c
1943    c
1944    c
1945    c
1946    c
1947    c
1948    c
1949    c
1950    c
1951    c
1952    c
1953    c
1954    c
1955    c
1956    c
1957    c
1958    c
1959    c
1960    c
1961    c
1962    c
1963    c
1964    c
1965    c
1966    c
1967    c
1968    c
1969    c
1970    c
1971    c
1972    c
1973    c
1974    c
1975    c
1976    c
1977    c
1978    c
1979    c
1980    c
1981    c
1982    c
1983    c
1984    c
1985    c
1986    c
1987    c
1988    c
1989    c
1990    c
1991    c
1992    c
1993    c
1994    c
1995    c

In [212]:
eia["dataFlagDescription"].value_counts()

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    226
Name: count, dtype: int64

In [213]:
eia["dataFlagId"].value_counts()

dataFlagId
5.0    226
Name: count, dtype: int64

In [214]:
eia[["productId", "productName", "activityName", "activityId"]].drop_duplicates().sort_values("productName")

      productId     productName activityName  activityId
0            44  Primary energy   Production           1
81           44  Primary energy  Consumption           2
3726         29      Renewables     Capacity           7
3753         29      Renewables   Generation          12

In [215]:
eia.head(2)

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
0,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,NaN,NaN,million metric tons of oil equivalent,7.106881,MTOE
1,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,NaN,NaN,quadrillion Btu,0.282024,QBTU

In [216]:
#copie eia + redenumesc coloane

eia_std = eia.copy()
eia_std = eia_std.rename(columns={
    "period" : "year",
    "countryRegionId" : "country_iso3",
    "countryRegionName" : "country_name",
    "unitName" : "unit_name"

})

In [217]:
# curatam textul
for col in ['productName', 'activityName', 'unit_name']:
    eia_std[col] = (
        eia_std[col]
            .astype(str)
            .str.strip()
            .str.lower()
            .str.replace(r'\s+', '_', regex=True)
    )

In [218]:
eia_std.head(2)

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit
0,2023,44,primary_energy,1,production,AUT,Austria,c,Country,NaN,NaN,million_metric_tons_of_oil_equivalent,7.106881,MTOE
1,2023,44,primary_energy,1,production,AUT,Austria,c,Country,NaN,NaN,quadrillion_btu,0.282024,QBTU

In [219]:
# construire indicator_name 
eia_std['indicator_name'] = (
    eia_std['productName'] + '_' + eia_std['activityName']
)
eia_std.indicator_name.unique()

array(['primary_energy_production', 'primary_energy_consumption',
       'renewables_capacity', 'renewables_generation'], dtype=object)

In [220]:
# unele sunt dubluri - population_population
# Folosim .loc
eia_std.loc[
    eia_std['productName'] == eia_std['activityName'],
    'indicator_name'
] = eia_std['productName']
 
eia_std.indicator_name.unique()

array(['primary_energy_production', 'primary_energy_consumption',
       'renewables_capacity', 'renewables_generation'], dtype=object)

In [221]:
# construire indicator_code
eia_std['indicator_code'] = (
    eia_std['productName'].str[:4].str.upper() + "_" +
    eia_std['activityName'].str[:3].str.upper()
)
eia_std['indicator_code'].unique()

array(['PRIM_PRO', 'PRIM_CON', 'RENE_CAP', 'RENE_GEN'], dtype=object)

In [222]:
eia_std['indicator_label'] = (
    eia_std['productName'].str.replace('_', ' ').str.title()
    + " - " +
    eia_std['activityName'].str.replace('_', ' ').str.title()
)
eia_std.indicator_label.unique()

array(['Primary Energy - Production', 'Primary Energy - Consumption',
       'Renewables - Capacity', 'Renewables - Generation'], dtype=object)

In [223]:
# underscore
eia_std['countryRegionTypeName'] = eia_std['countryRegionTypeName'].str.lower()

In [224]:
eia_std.head()

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,44,primary_energy,1,production,AUT,Austria,c,country,NaN,NaN,million_metric_tons_of_oil_equivalent,7.106881,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,44,primary_energy,1,production,AUT,Austria,c,country,NaN,NaN,quadrillion_btu,0.282024,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production
2,2023,44,primary_energy,1,production,AUT,Austria,c,country,NaN,NaN,terajoules,297550.897927,TJ,primary_energy_production,PRIM_PRO,Primary Energy - Production
3,2023,44,primary_energy,1,production,BEL,Belgium,c,country,NaN,NaN,million_metric_tons_of_oil_equivalent,11.706181,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
4,2023,44,primary_energy,1,production,BEL,Belgium,c,country,NaN,NaN,quadrillion_btu,0.464539,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [225]:
eia_std.dataFlagDescription.value_counts()

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    226
Name: count, dtype: int64

In [226]:
#verificam lipsuri dataflagdescription, valori inutile,  = 0
missing_pct = (
    eia_std.groupby('dataFlagDescription')['value']
           .apply(lambda x: x.isna().mean())
           .sort_values(ascending=False)
)
 
print((missing_pct * 100).round(2))

dataFlagDescription
A value exists, but rounds to zero; non-rounded values appear when downloaded    0.0
Name: value, dtype: float64

In [227]:
#lipsuri pe ani - 0
missing_by_year = (
    eia_std.groupby('year')['value']
           .apply(lambda x: x.isna().mean())
)
print("\nLipsuri pe an (%):")
print((missing_by_year * 100).round(2).head(20))

Lipsuri pe an (%):
year
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
Name: value, dtype: float64

In [228]:
eia_std.head(2)

,year,productId,productName,activityId,activityName,country_iso3,country_name,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,44,primary_energy,1,production,AUT,Austria,c,country,NaN,NaN,million_metric_tons_of_oil_equivalent,7.106881,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,44,primary_energy,1,production,AUT,Austria,c,country,NaN,NaN,quadrillion_btu,0.282024,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [229]:
eia_std["countryRegionTypeId"].value_counts() #stergem coloana

countryRegionTypeId
c    6831
Name: count, dtype: int64

In [230]:
eia_std["countryRegionTypeName"].value_counts() #stergem coloana

countryRegionTypeName
country    6831
Name: count, dtype: int64

In [231]:
cols_to_drop = [
    "productId", #inutil
    "productName", #redundant
    "activityId", #inutil
    "activityName", #redundant
    "countryRegionTypeId", #inutil
    "countryRegionTypeName", #inutil
    "dataFlagId", #inutil
    "dataFlagDescription" #inutil

]

eia_clean = eia_std.drop(columns = cols_to_drop)

In [232]:
eia_clean.head(2)

,year,country_iso3,country_name,unit_name,value,unit,indicator_name,indicator_code,indicator_label
0,2023,AUT,Austria,million_metric_tons_of_oil_equivalent,7.106881,MTOE,primary_energy_production,PRIM_PRO,Primary Energy - Production
1,2023,AUT,Austria,quadrillion_btu,0.282024,QBTU,primary_energy_production,PRIM_PRO,Primary Energy - Production

In [233]:
# randuri goale + duplicate
eia_clean = eia_clean.dropna(how='all')
eia_clean = eia_clean.drop_duplicates(keep='first')

In [234]:
# aranjam coloanele similar wdi
 
eia_clean= eia_clean[[
    'country_iso3',
    'country_name',
    'year',
    'indicator_code',
    'indicator_name',
    'indicator_label',
    'unit',
    'unit_name',
    'value'
]].copy()

In [235]:
eia_clean.to_csv("eia_eu_clean.csv", index=False)

In [236]:
wdi = pd.read_csv(r"C:\Users\ASUS\Desktop\ADC 2\FLUXURI DE LUCRU PENTRU STIINTA DATELOR\Data\wdi_EU.csv")

In [237]:
wdi.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'country_code', 'country', 'year',
       'gdp_per_capita', 'population', 'urbanization_rate',
       'energy_use_per_capita', 'renewable_final_share', 'electricity_access',
       'investment_energy', 'gov_effectiveness', 'regulatory_quality',
       'rule_of_law', 'control_corruption', 'CO2_emissions_proc',
       'CO2_emissions_mt', 'N2O_emissions_proc', 'N2O_emissions_mt',
       'CH4_emissions_proc', 'CH4_emissions_mt'],
      dtype='object')

In [238]:
wdi.head(3)

,Unnamed: 0.1,Unnamed: 0,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,...,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,950,950,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,...,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,951,951,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,...,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199
2,952,952,AUT,Austria,2002,26334.862215,8081957.0,59.655,3771.719492,24.7,...,1.880228,1.538056,1.857913,1.915159,18.935725,73.2160,-6.115108,4.0194,-20.234970,11.3043

In [239]:
wdi["Unnamed: 0"].value_counts

<bound method IndexOpsMixin.value_counts of 0        950
1        951
2        952
3        953
4        954
5        955
6        956
7        957
8        958
9        959
10       960
11       961
12       962
13       963
14       964
15       965
16       966
17       967
18       968
19       969
20       970
21       971
22       972
23       973
24      1470
25      1471
26      1472
27      1473
28      1474
29      1475
30      1476
31      1477
32      1478
33      1479
34      1480
35      1481
36      1482
37      1483
38      1484
39      1485
40      1486
41      1487
42      1488
43      1489
44      1490
45      1491
46      1492
47      1493
48      1600
49      1601
50      1602
51      1603
52      1604
53      1605
54      1606
55      1607
56      1608
57      1609
58      1610
59      1611
60      1612
61      1613
62      1614
63      1615
64      1616
65      1617
66      1618
67      1619
68      1620
69      1621
70      1622
71      1623
72      3355
73      3356
74      3357
75      3358
76      3359
77      3360
78      3361
79      3362
80      3363
81      3364
82      3365
83      3366
84      3367
85      3368
86      3369
87      3370
88      3371
89      3372
90      3373
91      3374
92      3375
93      3376
94      3377
95      3378
96      3420
97      3421
98      3422
99      3423
100     3424
101     3425
102     3426
103     3427
104     3428
105     3429
106     3430
107     3431
108     3432
109     3433
110     3434
111     3435
112     3436
113     3437
114     3438
115     3439
116     3440
117     3441
118     3442
119     3443
120     3485
121     3486
122     3487
123     3488
124     3489
125     3490
126     3491
127     3492
128     3493
129     3494
130     3495
131     3496
132     3497
133     3498
134     3499
135     3500
136     3501
137     3502
138     3503
139     3504
140     3505
141     3506
142     3507
143     3508
144     3615
145     3616
146     3617
147     3618
148     3619
149     3620
150     3621
151     3622
152     3623
153     3624
154     3625
155     3626
156     3627
157     3628
158     3629
159     3630
160     3631
161     3632
162     3633
163     3634
164     3635
165     3636
166     3637
167     3638
168     3940
169     3941
170     3942
171     3943
172     3944
173     3945
174     3946
175     3947
176     3948
177     3949
178     3950
179     3951
180     3952
181     3953
182     3954
183     3955
184     3956
185     3957
186     3958
187     3959
188     3960
189     3961
190     3962
191     3963
192     4135
193     4136
194     4137
195     4138
196     4139
197     4140
198     4141
199     4142
200     4143
201     4144
202     4145
203     4146
204     4147
205     4148
206     4149
207     4150
208     4151
209     4152
210     4153
211     4154
212     4155
213     4156
214     4157
215     4158
216     4395
217     4396
218     4397
219     4398
220     4399
221     4400
222     4401
223     4402
224     4403
225     4404
226     4405
227     4406
228     4407
229     4408
230     4409
231     4410
232     4411
233     4412
234     4413
235     4414
236     4415
237     4416
238     4417
239     4418
240     4655
241     4656
242     4657
243     4658
244     4659
245     4660
246     4661
247     4662
248     4663
249     4664
250     4665
251     4666
252     4667
253     4668
254     4669
255     4670
256     4671
257     4672
258     4673
259     4674
260     4675
261     4676
262     4677
263     4678
264     5370
265     5371
266     5372
267     5373
268     5374
269     5375
270     5376
271     5377
272     5378
273     5379
274     5380
275     5381
276     5382
277     5383
278     5384
279     5385
280     5386
281     5387
282     5388
283     5389
284     5390
285     5391
286     5392
287     5393
288     5825
289     5826
290     5827
291     5828
292     5829
293     5830
294     5831
295     5832
296     5833
297     5834
298     5835
299     5836
300     5837
301     5838
302     5839
303     5840
304     5841
305     5842
306     5843
307     5844
308     5845
309     5846
310     5847
311     5848
312     5955
313     5956
314     5957
315     5958
316     5959
317     5960
318     5961
319     5962
320     5963
321     5964
322     5965
323     5966
324     5967
325     5968
326     5969
327     5970
328     5971
329     5972
330     5973
331     5974
332     5975
333     5976
334     5977
335     5978
336     6085
337     6086
338     6087
339     6088
340     6089
341     6090
342     6091
343     6092
344     6093
345     6094
346     6095
347     6096
348     6097
349     6098
350     6099
351     6100
352     6101
353     6102
354     6103
355     6104
356     6105
357     6106
358     6107
359     6108
360     6540
361     6541
362     6542
363     6543
364     6544
365     6545
366     6546
367     6547
368     6548
369     6549
370     6550
371     6551
372     6552
373     6553
374     6554
375     6555
376     6556
377     6557
378     6558
379     6559
380     6560
381     6561
382     6562
383     6563
384     8035
385     8036
386     8037
387     8038
388     8039
389     8040
390     8041
391     8042
392     8043
393     8044
394     8045
395     8046
396     8047
397     8048
398     8049
399     8050
400     8051
401     8052
402     8053
403     8054
404     8055
405     8056
406     8057
407     8058
408     8100
409     8101
410     8102
411     8103
412     8104
413     8105
414     8106
415     8107
416     8108
417     8109
418     8110
419     8111
420     8112
421     8113
422     8114
423     8115
424     8116
425     8117
426     8118
427     8119
428     8120
429     8121
430     8122
431     8123
432     8165
433     8166
434     8167
435     8168
436     8169
437     8170
438     8171
439     8172
440     8173
441     8174
442     8175
443     8176
444     8177
445     8178
446     8179
447     8180
448     8181
449     8182
450     8183
451     8184
452     8185
453     8186
454     8187
455     8188
456     9205
457     9206
458     9207
459     9208
460     9209
461     9210
462     9211
463     9212
464     9213
465     9214
466     9215
467     9216
468     9217
469     9218
470     9219
471     9220
472     9221
473     9222
474     9223
475     9224
476     9225
477     9226
478     9227
479     9228
480     9985
481     9986
482     9987
483     9988
484     9989
485     9990
486     9991
487     9992
488     9993
489     9994
490     9995
491     9996
492     9997
493     9998
494     9999
495    10000
496    10001
497    10002
498    10003
499    10004
500    10005
501    10006
502    10007
503    10008
504    10830
505    10831
506    10832
507    10833
508    10834
509    10835
510    10836
511    10837
512    10838
513    10839
514    10840
515    10841
516    10842
517    10843
518    10844
519    10845
520    10846
521    10847
522    10848
523    10849
524    10850
525    10851
526    10852
527    10853
528    11025
529    11026
530    11027
531    11028
532    11029
533    11030
534    11031
535    11032
536    11033
537    11034
538    11035
539    11036
540    11037
541    11038
542    11039
543    11040
544    11041
545    11042
546    11043
547    11044
548    11045
549    11046
550    11047
551    11048
552    11285
553    11286
554    11287
555    11288
556    11289
557    11290
558    11291
559    11292
560    11293
561    11294
562    11295
563    11296
564    11297
565    11298
566    11299
567    11300
568    11301
569    11302
570    11303
571    11304
572    11305
573    11306
574    11307
575    11308
576    12065
577    12066
578    12067
579    12068
580    12069
581    12070
582    12071
583    12072
584    12073
585    12074
586    12075
587    12076
588    12077
589    12078
590    12079
591    12080
592    12081
593    12082
594    12083
595    12084
596    12085
597    12086
598    12087
599    12088
600    12195
601    12196
602    12197
603    12198
604    12199
605    12200
606    12201
607    12202
608    12203
609    12204
610    12205
611    12206
612    12207
613    12208
614    12209
615    12210
616    12211
617    12212
618    12213
619    12214
620    12215
621    12216
622    12217
623    12218
624    12260
625    12261
626    12262
627    12263
628    12264
629    12265
630    12266
631    12267
632    12268
633    12269
634    12270
635    12271
636    12272
637    12273
638    12274
639    12275
640    12276
641    12277
642    12278
643    12279
644    12280
645    12281
646    12282
647    12283
Name: Unnamed: 0, dtype: int64>

In [240]:
cols_to_drop = [
    "Unnamed: 0.1",
    "Unnamed: 0"
]

wdi_clean = wdi.drop(columns = cols_to_drop)

In [241]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [242]:
#media na-uri
wdi_clean.isna().mean().sort_values(ascending=False)

investment_energy        0.962963
renewable_final_share    0.083333
regulatory_quality       0.041667
gov_effectiveness        0.041667
control_corruption       0.041667
rule_of_law              0.041667
country                  0.000000
country_code             0.000000
gdp_per_capita           0.000000
year                     0.000000
energy_use_per_capita    0.000000
urbanization_rate        0.000000
electricity_access       0.000000
population               0.000000
CO2_emissions_proc       0.000000
CO2_emissions_mt         0.000000
N2O_emissions_proc       0.000000
N2O_emissions_mt         0.000000
CH4_emissions_proc       0.000000
CH4_emissions_mt         0.000000
dtype: float64

In [243]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,MTOE,million_metric_tons_of_oil_equivalent,7.106881
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,QBTU,quadrillion_btu,0.282024

In [244]:
cols_to_drop = [
    "unit"    
]

eia_clean = eia_clean.drop(columns = cols_to_drop)

In [245]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,million_metric_tons_of_oil_equivalent,7.106881
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,quadrillion_btu,0.282024

In [246]:
eia_clean["unit_name"].value_counts

<bound method IndexOpsMixin.value_counts of 0       million_metric_tons_of_oil_equivalent
1                             quadrillion_btu
2                                  terajoules
3       million_metric_tons_of_oil_equivalent
4                             quadrillion_btu
5                                  terajoules
6       million_metric_tons_of_oil_equivalent
7                             quadrillion_btu
8                                  terajoules
9       million_metric_tons_of_oil_equivalent
10                            quadrillion_btu
11                                 terajoules
12      million_metric_tons_of_oil_equivalent
13                            quadrillion_btu
14                                 terajoules
15      million_metric_tons_of_oil_equivalent
16                            quadrillion_btu
17                                 terajoules
18      million_metric_tons_of_oil_equivalent
19                            quadrillion_btu
20                                 terajoules
21      million_metric_tons_of_oil_equivalent
22                            quadrillion_btu
23                                 terajoules
24      million_metric_tons_of_oil_equivalent
25                            quadrillion_btu
26                                 terajoules
27      million_metric_tons_of_oil_equivalent
28                            quadrillion_btu
29                                 terajoules
30      million_metric_tons_of_oil_equivalent
31                            quadrillion_btu
32                                 terajoules
33      million_metric_tons_of_oil_equivalent
34                            quadrillion_btu
35                                 terajoules
36      million_metric_tons_of_oil_equivalent
37                            quadrillion_btu
38                                 terajoules
39      million_metric_tons_of_oil_equivalent
40                            quadrillion_btu
41                                 terajoules
42      million_metric_tons_of_oil_equivalent
43                            quadrillion_btu
44                                 terajoules
45      million_metric_tons_of_oil_equivalent
46                            quadrillion_btu
47                                 terajoules
48      million_metric_tons_of_oil_equivalent
49                            quadrillion_btu
50                                 terajoules
51      million_metric_tons_of_oil_equivalent
52                            quadrillion_btu
53                                 terajoules
54      million_metric_tons_of_oil_equivalent
55                            quadrillion_btu
56                                 terajoules
57      million_metric_tons_of_oil_equivalent
58                            quadrillion_btu
59                                 terajoules
60      million_metric_tons_of_oil_equivalent
61                            quadrillion_btu
62                                 terajoules
63      million_metric_tons_of_oil_equivalent
64                            quadrillion_btu
65                                 terajoules
66      million_metric_tons_of_oil_equivalent
67                            quadrillion_btu
68                                 terajoules
69      million_metric_tons_of_oil_equivalent
70                            quadrillion_btu
71                                 terajoules
72      million_metric_tons_of_oil_equivalent
73                            quadrillion_btu
74                                 terajoules
75      million_metric_tons_of_oil_equivalent
76                            quadrillion_btu
77                                 terajoules
78      million_metric_tons_of_oil_equivalent
79                            quadrillion_btu
80                                 terajoules
81      million_metric_tons_of_oil_equivalent
82                            quadrillion_btu
83                                 terajoules
84      million_metric_tons_of_oil_equivalent
85                            quadrillion_btu
86                                 terajoules
87      million_metric_tons_of_oil_equivalent
88                            quadrillion_btu
89                                 terajoules
90      million_metric_tons_of_oil_equivalent
91                            quadrillion_btu
92                                 terajoules
93      million_metric_tons_of_oil_equivalent
94                            quadrillion_btu
95                                 terajoules
96      million_metric_tons_of_oil_equivalent
97                            quadrillion_btu
98                                 terajoules
99      million_metric_tons_of_oil_equivalent
100                           quadrillion_btu
101                                terajoules
102     million_metric_tons_of_oil_equivalent
103                           quadrillion_btu
104                                terajoules
105     million_metric_tons_of_oil_equivalent
106                           quadrillion_btu
107                                terajoules
108     million_metric_tons_of_oil_equivalent
109                           quadrillion_btu
110                                terajoules
111     million_metric_tons_of_oil_equivalent
112                           quadrillion_btu
113                                terajoules
114     million_metric_tons_of_oil_equivalent
115                           quadrillion_btu
116                                terajoules
117     million_metric_tons_of_oil_equivalent
118                           quadrillion_btu
119                                terajoules
120     million_metric_tons_of_oil_equivalent
121                           quadrillion_btu
122                                terajoules
123     million_metric_tons_of_oil_equivalent
124                           quadrillion_btu
125                                terajoules
126     million_metric_tons_of_oil_equivalent
127                           quadrillion_btu
128                                terajoules
129     million_metric_tons_of_oil_equivalent
130                           quadrillion_btu
131                                terajoules
132     million_metric_tons_of_oil_equivalent
133                           quadrillion_btu
134                                terajoules
135     million_metric_tons_of_oil_equivalent
136                           quadrillion_btu
137                                terajoules
138     million_metric_tons_of_oil_equivalent
139                           quadrillion_btu
140                                terajoules
141     million_metric_tons_of_oil_equivalent
142                           quadrillion_btu
143                                terajoules
144     million_metric_tons_of_oil_equivalent
145                           quadrillion_btu
146                                terajoules
147     million_metric_tons_of_oil_equivalent
148                           quadrillion_btu
149                                terajoules
150     million_metric_tons_of_oil_equivalent
151                           quadrillion_btu
152                                terajoules
153     million_metric_tons_of_oil_equivalent
154                           quadrillion_btu
155                                terajoules
156     million_metric_tons_of_oil_equivalent
157                           quadrillion_btu
158                                terajoules
159     million_metric_tons_of_oil_equivalent
160                           quadrillion_btu
161                                terajoules
162     million_metric_tons_of_oil_equivalent
163                           quadrillion_btu
164                                terajoules
165     million_metric_tons_of_oil_equivalent
166                           quadrillion_btu
167                                terajoules
168     million_metric_tons_of_oil_equivalent
169                           quadrillion_btu
170                                terajoules
171     million_metric_tons_of_oil_equivalent
172                           quadrillion_btu
173                                terajoules
174     million_metric_tons_of_oil_equivalent
175                           quadrillion_btu
176                                terajoules
177     million_metric_tons_of_oil_equivalent
178                           quadrillion_btu
179                                terajoules
180     million_metric_tons_of_oil_equivalent
181                           quadrillion_btu
182                                terajoules
183     million_metric_tons_of_oil_equivalent
184                           quadrillion_btu
185                                terajoules
186     million_metric_tons_of_oil_equivalent
187                           quadrillion_btu
188                                terajoules
189     million_metric_tons_of_oil_equivalent
190                           quadrillion_btu
191                                terajoules
192     million_metric_tons_of_oil_equivalent
193                           quadrillion_btu
194                                terajoules
195     million_metric_tons_of_oil_equivalent
196                           quadrillion_btu
197                                terajoules
198     million_metric_tons_of_oil_equivalent
199                           quadrillion_btu
200                                terajoules
201     million_metric_tons_of_oil_equivalent
202                           quadrillion_btu
203                                terajoules
204     million_metric_tons_of_oil_equivalent
205                           quadrillion_btu
206                                terajoules
207     million_metric_tons_of_oil_equivalent
208                           quadrillion_btu
209                                terajoules
210     million_metric_tons_of_oil_equivalent
211                           quadrillion_btu
212                                terajoules
213     million_metric_tons_of_oil_equivalent
214                           quadrillion_btu
215                                terajoules
216     million_metric_tons_of_oil_equivalent
217                           quadrillion_btu
218                                terajoules
219     million_metric_tons_of_oil_equivalent
220                           quadrillion_btu
221                                terajoules
222     million_metric_tons_of_oil_equivalent
223                           quadrillion_btu
224                                terajoules
225     million_metric_tons_of_oil_equivalent
226                           quadrillion_btu
227                                terajoules
228     million_metric_tons_of_oil_equivalent
229                           quadrillion_btu
230                                terajoules
231     million_metric_tons_of_oil_equivalent
232                           quadrillion_btu
233                                terajoules
234     million_metric_tons_of_oil_equivalent
235                           quadrillion_btu
236                                terajoules
237     million_metric_tons_of_oil_equivalent
238                           quadrillion_btu
239                                terajoules
240     million_metric_tons_of_oil_equivalent
241                           quadrillion_btu
242                                terajoules
243     million_metric_tons_of_oil_equivalent
244                           quadrillion_btu
245                                terajoules
246     million_metric_tons_of_oil_equivalent
247                           quadrillion_btu
248                                terajoules
249     million_metric_tons_of_oil_equivalent
250                           quadrillion_btu
251                                terajoules
252     million_metric_tons_of_oil_equivalent
253                           quadrillion_btu
254                                terajoules
255     million_metric_tons_of_oil_equivalent
256                           quadrillion_btu
257                                terajoules
258     million_metric_tons_of_oil_equivalent
259                           quadrillion_btu
260                                terajoules
261     million_metric_tons_of_oil_equivalent
262                           quadrillion_btu
263                                terajoules
264     million_metric_tons_of_oil_equivalent
265                           quadrillion_btu
266                                terajoules
267     million_metric_tons_of_oil_equivalent
268                           quadrillion_btu
269                                terajoules
270     million_metric_tons_of_oil_equivalent
271                           quadrillion_btu
272                                terajoules
273     million_metric_tons_of_oil_equivalent
274                           quadrillion_btu
275                                terajoules
276     million_metric_tons_of_oil_equivalent
277                           quadrillion_btu
278                                terajoules
279     million_metric_tons_of_oil_equivalent
280                           quadrillion_btu
281                                terajoules
282     million_metric_tons_of_oil_equivalent
283                           quadrillion_btu
284                                terajoules
285     million_metric_tons_of_oil_equivalent
286                           quadrillion_btu
287                                terajoules
288     million_metric_tons_of_oil_equivalent
289                           quadrillion_btu
290                                terajoules
291     million_metric_tons_of_oil_equivalent
292                           quadrillion_btu
293                                terajoules
294     million_metric_tons_of_oil_equivalent
295                           quadrillion_btu
296                                terajoules
297     million_metric_tons_of_oil_equivalent
298                           quadrillion_btu
299                                terajoules
300     million_metric_tons_of_oil_equivalent
301                           quadrillion_btu
302                                terajoules
303     million_metric_tons_of_oil_equivalent
304                           quadrillion_btu
305                                terajoules
306     million_metric_tons_of_oil_equivalent
307                           quadrillion_btu
308                                terajoules
309     million_metric_tons_of_oil_equivalent
310                           quadrillion_btu
311                                terajoules
312     million_metric_tons_of_oil_equivalent
313                           quadrillion_btu
314                                terajoules
315     million_metric_tons_of_oil_equivalent
316                           quadrillion_btu
317                                terajoules
318     million_metric_tons_of_oil_equivalent
319                           quadrillion_btu
320                                terajoules
321     million_metric_tons_of_oil_equivalent
322                           quadrillion_btu
323                                terajoules
324     million_metric_tons_of_oil_equivalent
325                           quadrillion_btu
326                                terajoules
327     million_metric_tons_of_oil_equivalent
328                           quadrillion_btu
329                                terajoules
330     million_metric_tons_of_oil_equivalent
331                           quadrillion_btu
332                                terajoules
333     million_metric_tons_of_oil_equivalent
334                           quadrillion_btu
335                                terajoules
336     million_metric_tons_of_oil_equivalent
337                           quadrillion_btu
338                                terajoules
339     million_metric_tons_of_oil_equivalent
340                           quadrillion_btu
341                                terajoules
342     million_metric_tons_of_oil_equivalent
343                           quadrillion_btu
344                                terajoules
345     million_metric_tons_of_oil_equivalent
346                           quadrillion_btu
347                                terajoules
348     million_metric_tons_of_oil_equivalent
349                           quadrillion_btu
350                                terajoules
351     million_metric_tons_of_oil_equivalent
352                           quadrillion_btu
353                                terajoules
354     million_metric_tons_of_oil_equivalent
355                           quadrillion_btu
356                                terajoules
357     million_metric_tons_of_oil_equivalent
358                           quadrillion_btu
359                                terajoules
360     million_metric_tons_of_oil_equivalent
361                           quadrillion_btu
362                                terajoules
363     million_metric_tons_of_oil_equivalent
364                           quadrillion_btu
365                                terajoules
366     million_metric_tons_of_oil_equivalent
367                           quadrillion_btu
368                                terajoules
369     million_metric_tons_of_oil_equivalent
370                           quadrillion_btu
371                                terajoules
372     million_metric_tons_of_oil_equivalent
373                           quadrillion_btu
374                                terajoules
375     million_metric_tons_of_oil_equivalent
376                           quadrillion_btu
377                                terajoules
378     million_metric_tons_of_oil_equivalent
379                           quadrillion_btu
380                                terajoules
381     million_metric_tons_of_oil_equivalent
382                           quadrillion_btu
383                                terajoules
384     million_metric_tons_of_oil_equivalent
385                           quadrillion_btu
386                                terajoules
387     million_metric_tons_of_oil_equivalent
388                           quadrillion_btu
389                                terajoules
390     million_metric_tons_of_oil_equivalent
391                           quadrillion_btu
392                                terajoules
393     million_metric_tons_of_oil_equivalent
394                           quadrillion_btu
395                                terajoules
396     million_metric_tons_of_oil_equivalent
397                           quadrillion_btu
398                                terajoules
399     million_metric_tons_of_oil_equivalent
400                           quadrillion_btu
401                                terajoules
402     million_metric_tons_of_oil_equivalent
403                           quadrillion_btu
404                                terajoules
405     million_metric_tons_of_oil_equivalent
406                           quadrillion_btu
407                                terajoules
408     million_metric_tons_of_oil_equivalent
409                           quadrillion_btu
410                                terajoules
411     million_metric_tons_of_oil_equivalent
412                           quadrillion_btu
413                                terajoules
414     million_metric_tons_of_oil_equivalent
415                           quadrillion_btu
416                                terajoules
417     million_metric_tons_of_oil_equivalent
418                           quadrillion_btu
419                                terajoules
420     million_metric_tons_of_oil_equivalent
421                           quadrillion_btu
422                                terajoules
423     million_metric_tons_of_oil_equivalent
424                           quadrillion_btu
425                                terajoules
426     million_metric_tons_of_oil_equivalent
427                           quadrillion_btu
428                                terajoules
429     million_metric_tons_of_oil_equivalent
430                           quadrillion_btu
431                                terajoules
432     million_metric_tons_of_oil_equivalent

In [247]:
pd.set_option('display.max_rows', None)
 
all_indicators = eia_clean[["indicator_name", "unit_name"]].drop_duplicates()
# all_indicators are coloane: indicator_name, unit_name
# Vrem pentru fiecare indicator lista de unități distincte
 
units_per_indicator = (
    all_indicators
    .groupby("indicator_name")["unit_name"]
    .unique()
)
units_per_indicator

indicator_name
primary_energy_consumption    [million_metric_tons_of_oil_equivalent, quadri...
primary_energy_production     [million_metric_tons_of_oil_equivalent, quadri...
renewables_capacity                                         [million_kilowatts]
renewables_generation         [billion_kilowatthours, million_metric_tons_of...
Name: unit_name, dtype: object

In [248]:
# Selectăm doar indicatorii care au mai multe unități
multi_unit_indicators = units_per_indicator[units_per_indicator.apply(len) > 1]
 
# Print frumos
for ind, units in multi_unit_indicators.items():
    print(f"$ {ind}:")
    for u in units:
        print(f"   • {u}")

$ primary_energy_consumption:
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules
$ primary_energy_production:
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules
$ renewables_generation:
   • billion_kilowatthours
   • million_metric_tons_of_oil_equivalent
   • quadrillion_btu
   • terajoules

In [249]:
# 1. unitățile standard
preferred_units = {
    "renewables_generation": "billion_kilowatthours",
    "primary_energy_consumption": "million_metric_tons_of_oil_equivalent",
    "primary_energy_production": "million_metric_tons_of_oil_equivalent",
}
 
# 2. tabel unic de conversie
CONVERSION = {
    # ---- electricitate ----
    ("billion_kilowatthours", "billion_kilowatthours"): 1,
    ("billion_kilowatthours", "million_metric_tons_of_oil_equivalent"): 11.63,
    ("billion_kilowatthours", "quadrillion_btu"): 293.071,
    ("billion_kilowatthours", "terajoules"): 277.778,

    # ---- energie primară ----
    ("million_metric_tons_of_oil_equivalent", "million_metric_tons_of_oil_equivalent"): 1,
    ("million_metric_tons_of_oil_equivalent", "quadrillion_btu"): 25.2,
    ("million_metric_tons_of_oil_equivalent", "terajoules"): 41_868,
}

In [250]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,million_metric_tons_of_oil_equivalent,7.106881
1,AUT,Austria,2023,PRIM_PRO,primary_energy_production,Primary Energy - Production,quadrillion_btu,0.282024

In [251]:
# -------------------------------------------------------------
eia_f = eia_clean.copy()
 
for ind, unit in preferred_units.items():
    # pentru indicatorul ind, păstrăm doar rândurile cu unit=preferată
    eia_f = eia_f[
        ~(
            (eia_f["indicator_name"] == ind) &
            (eia_f["unit_name"] != unit)
        )
    ]
 
# -------------------------------------------------------------
# 3. Pentru ceilalți indicatori → păstrăm doar o unitate (prima)
# -------------------------------------------------------------
other_inds = set(eia_f["indicator_name"]) - set(preferred_units.keys())
 
rows = []
for ind in other_inds:
    sub = eia_f[eia_f["indicator_name"] == ind]
    first_unit = sub["unit_name"].iloc[0]
    rows.append(sub[sub["unit_name"] == first_unit])
 
eia_f2 = pd.concat(rows, ignore_index=True)
 
# Adăugăm și indicatorii standardizați deja
eia_clean = pd.concat([
    eia_f2,
    eia_f[eia_f["indicator_name"].isin(preferred_units.keys())]
], ignore_index=True)
 
# -------------------------------------------------------------
# 4. Test: verificăm dacă fiecare indicator are o singură unitate
# -------------------------------------------------------------
print(
    eia_clean.groupby("indicator_name")["unit_name"].nunique().sort_values(ascending=False)
)

indicator_name
primary_energy_consumption    1
primary_energy_production     1
renewables_capacity           1
renewables_generation         1
Name: unit_name, dtype: int64

In [252]:
eia_clean.head(2)

,country_iso3,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,21.132915
1,BEL,Belgium,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,15.047000

In [253]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,investment_energy,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,NaN,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [254]:
eia_clean = eia_clean.rename(columns={"country_iso3": "country_code"})

In [255]:
cols_to_drop = [
    "investment_energy"    
]

wdi_clean = wdi_clean.drop(columns = cols_to_drop)

In [256]:
wdi_clean.head(2)

,country_code,country,year,gdp_per_capita,population,urbanization_rate,energy_use_per_capita,renewable_final_share,electricity_access,gov_effectiveness,regulatory_quality,rule_of_law,control_corruption,CO2_emissions_proc,CO2_emissions_mt,N2O_emissions_proc,N2O_emissions_mt,CH4_emissions_proc,CH4_emissions_mt
0,AUT,Austria,2000,24487.297469,8011566.0,60.213,3570.948532,26.4,100.0,1.847265,1.475476,1.812333,1.751059,8.335702,66.6907,-5.935252,4.0271,-19.682472,11.3826
1,AUT,Austria,2001,24430.495983,8042293.0,59.934,3758.793163,25.5,100.0,NaN,NaN,NaN,NaN,15.946738,71.3760,-4.512753,4.0880,-20.124894,11.3199

In [257]:
eia_clean.head(2)

,country_code,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,21.132915
1,BEL,Belgium,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,15.047000

In [258]:
wdi_clean_1 = wdi_clean.melt(
    id_vars=['country_code', 'country', 'year'],
    var_name='indicator_name',
    value_name='value'
)

In [259]:
wdi_clean_1.head(2)

  country_code  country  year  indicator_name         value
0          AUT  Austria  2000  gdp_per_capita  24487.297469
1          AUT  Austria  2001  gdp_per_capita  24430.495983

In [260]:
indicator_units = {

    "gdp_per_capita": "current US$ per capita",

    "population": "persons",

    "urbanization_rate": "percent of total population",

    "energy_use_per_capita": "kg of oil equivalent per capita",

    "renewable_final_share": "percent of final energy consumption",

    "electricity_access": "percent of population",

    "gov_effectiveness": "index",

    "regulatory_quality": "index",

    "rule_of_law": "index",

    "control_corruption": "index",

    "CO2_emissions_proc": "percent of total GHG emissions",

    "CO2_emissions_mt": "million tonnes",

    "N2O_emissions_proc": "percent of total GHG emissions",

    "N2O_emissions_mt": "million tonnes",

    "CH4_emissions_proc": "percent of total GHG emissions",

    "CH4_emissions_mt": "million tonnes"

}

 
# creem coloana unit name pe baza dictionarului
wdi_clean_1["unit_name"] = wdi_clean_1["indicator_name"].map(indicator_units)
wdi_clean_1["unit_name"].isna().sum()

np.int64(0)

In [261]:
wdi_clean_1.head(2)

,country_code,country,year,indicator_name,value,unit_name
0,AUT,Austria,2000,gdp_per_capita,24487.297469,current US$ per capita
1,AUT,Austria,2001,gdp_per_capita,24430.495983,current US$ per capita

In [262]:
eia_clean.head(2)

,country_code,country_name,year,indicator_code,indicator_name,indicator_label,unit_name,value
0,AUT,Austria,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,21.132915
1,BEL,Belgium,2023,RENE_CAP,renewables_capacity,Renewables - Capacity,million_kilowatts,15.047000

In [263]:
wdi_clean_1 = wdi_clean_1.rename(columns={"country": "country_name"})

In [264]:
wdi_clean_1.head(2)

,country_code,country_name,year,indicator_name,value,unit_name
0,AUT,Austria,2000,gdp_per_capita,24487.297469,current US$ per capita
1,AUT,Austria,2001,gdp_per_capita,24430.495983,current US$ per capita

In [265]:
# creem wdi final
wdi_final = wdi_clean_1[[
    "country_code",
    "country_name",
    "year",
    "indicator_name",
    "unit_name",
    "value"
]].copy()
 
# creem eia final
eia_final = eia_clean[[
    "country_code",
    "country_name",
    "year",
    "indicator_name",
    "unit_name",
    "value"
]].copy()
 
eia_final["value"] = pd.to_numeric(eia_final["value"], errors="coerce")

In [266]:
all_data_long = pd.concat([wdi_final, eia_final], ignore_index=True)

In [267]:
all_data_long.head(2)

,country_code,country_name,year,indicator_name,unit_name,value
0,AUT,Austria,2000,gdp_per_capita,current US$ per capita,24487.297469
1,AUT,Austria,2001,gdp_per_capita,current US$ per capita,24430.495983

In [268]:
all_data_long["indicator_name"].unique()

array(['gdp_per_capita', 'population', 'urbanization_rate',
       'energy_use_per_capita', 'renewable_final_share',
       'electricity_access', 'gov_effectiveness', 'regulatory_quality',
       'rule_of_law', 'control_corruption', 'CO2_emissions_proc',
       'CO2_emissions_mt', 'N2O_emissions_proc', 'N2O_emissions_mt',
       'CH4_emissions_proc', 'CH4_emissions_mt', 'renewables_capacity',
       'primary_energy_production', 'primary_energy_consumption',
       'renewables_generation'], dtype=object)